export default {
    "a-space": "<a-space>$1</a-space>",
    "a-button:type": "<a-button type=\"$1\">$2</a-button>",
    "a-button": "<a-button>$1</a-button>",
    "a-space:direction": "<a-space direction=\"$1\">$2</a-space>",
    "a-button:shape": "<a-button shape=\"$1\">$2</a-button>",
    "a-radio-group:v-model:value": "<a-radio-group v-model:value=\"$1\">$2</a-radio-group>",
    "a-radio-button:value": "<a-radio-button value=\"$1\">$2</a-radio-button>",
    "a-button:size": "<a-button :size=\"$1\">$2</a-button>",
    "a-tooltip:title": "<a-tooltip title=\"$1\">$2</a-tooltip>",
    "a-menu": "<a-menu>$1</a-menu>",
    "a-menu-item:key": "<a-menu-item key=\"$1\">$2</a-menu-item>",
    "a-typography-text": "<a-typography-text>$1</a-typography-text>",
    "a-typography-title:level": "<a-typography-title :level=\"$1\">$2</a-typography-title>",
    "a-typography-link": "<a-typography-link>$1</a-typography-link>",
    "a-divider": "<a-divider>$1</a-divider>",
    "a-switch:v-model:checked": "<a-switch v-model:checked=\"$1\">$2</a-switch>",
    "a-typography-paragraph:ellipsis": "<a-typography-paragraph :ellipsis=\"$1\">$2</a-typography-paragraph>",
    "a-typography-paragraph": "<a-typography-paragraph>$1</a-typography-paragraph>",
    "a-typography-paragraph:v-model:content": "<a-typography-paragraph v-model:content=\"$1\">$2</a-typography-paragraph>",
    "a-radio-group": "<a-radio-group>$1</a-radio-group>",
    "a-radio:value": "<a-radio value=\"$1\">$2</a-radio>",
    "a-typography-text:type": "<a-typography-text type=\"$1\">$2</a-typography-text>",
    "a-typography-link:target": "<a-typography-link target=\"$1\">$2</a-typography-link>",
    "a-slider:v-model:value": "<a-slider v-model:value=\"$1\">$2</a-slider>",
    "a-divider:type": "<a-divider type=\"$1\">$2</a-divider>",
    "a-divider:orientation": "<a-divider orientation=\"$1\">$2</a-divider>",
    "a-flex:gap": "<a-flex gap=\"$1\">$2</a-flex>",
    "a-flex": "<a-flex>$1</a-flex>",
    "a-segmented:v-model:value": "<a-segmented v-model:value=\"$1\">$2</a-segmented>",
    "a-flex:justify": "<a-flex :justify=\"$1\">$2</a-flex>",
    "a-flex:wrap": "<a-flex wrap=\"$1\">$2</a-flex>",
    "a-button:key": "<a-button :key=\"$1\">$2</a-button>",
    "a-card:style": "<a-card :style=\"$1\">$2</a-card>",
    "a-col:span": "<a-col :span=\"$1\">$2</a-col>",
    "a-row:gutter": "<a-row :gutter=\"$1\">$2</a-row>",
    "a-row": "<a-row>$1</a-row>",
    "a-row:justify": "<a-row justify=\"$1\">$2</a-row>",
    "a-row:align": "<a-row align=\"$1\">$2</a-row>",
    "a-col:flex": "<a-col :flex=\"$1\">$2</a-col>",
    "a-col": "<a-col>$1</a-col>",
    "a-row:wrap": "<a-row :wrap=\"$1\">$2</a-row>",
    "a-col:xs": "<a-col :xs=\"$1\">$2</a-col>",
    "a-tag:key": "<a-tag :key=\"$1\">$2</a-tag>",
    "a-layout-header:style": "<a-layout-header :style=\"$1\">$2</a-layout-header>",
    "a-layout-content:style": "<a-layout-content :style=\"$1\">$2</a-layout-content>",
    "a-layout-footer:style": "<a-layout-footer :style=\"$1\">$2</a-layout-footer>",
    "a-layout-sider:style": "<a-layout-sider :style=\"$1\">$2</a-layout-sider>",
    "a-layout:class": "<a-layout class=\"$1\">$2</a-layout>",
    "a-menu:v-model:selectedKeys": "<a-menu v-model:selectedKeys=\"$1\">$2</a-menu>",
    "a-layout-content": "<a-layout-content>$1</a-layout-content>",
    "a-breadcrumb": "<a-breadcrumb>$1</a-breadcrumb>",
    "a-layout-footer": "<a-layout-footer>$1</a-layout-footer>",
    "a-layout-header:class": "<a-layout-header class=\"$1\">$2</a-layout-header>",
    "a-layout-sider:width": "<a-layout-sider width=\"$1\">$2</a-layout-sider>",
    "a-sub-menu:key": "<a-sub-menu key=\"$1\">$2</a-sub-menu>",
    "a-layout": "<a-layout>$1</a-layout>",
    "a-layout-sider:v-model:collapsed": "<a-layout-sider v-model:collapsed=\"$1\">$2</a-layout-sider>",
    "a-layout-header": "<a-layout-header>$1</a-layout-header>",
    "a-layout-sider:breakpoint": "<a-layout-sider breakpoint=\"$1\">$2</a-layout-sider>",
    "a-layout-sider": "<a-layout-sider>$1</a-layout-sider>",
    "a-popconfirm:ok-text": "<a-popconfirm ok-text=\"$1\">$2</a-popconfirm>",
    "a-space:size": "<a-space :size=\"$1\">$2</a-space>",
    "a-card:title": "<a-card title=\"$1\">$2</a-card>",
    "a-space:align": "<a-space align=\"$1\">$2</a-space>",
    "a-space-compact": "<a-space-compact>$1</a-space-compact>",
    "a-input:default-value": "<a-input default-value=\"$1\">$2</a-input>",
    "a-space-compact:size": "<a-space-compact size=\"$1\">$2</a-space-compact>",
    "a-input": "<a-input>$1</a-input>",
    "a-tooltip": "<a-tooltip>$1</a-tooltip>",
    "a-select:default-value": "<a-select default-value=\"$1\">$2</a-select>",
    "a-select-option:value": "<a-select-option value=\"$1\">$2</a-select-option>",
    "a-select:mode": "<a-select mode=\"$1\">$2</a-select>",
    "a-input-search:default-value": "<a-input-search default-value=\"$1\">$2</a-input-search>",
    "a-input-search": "<a-input-search>$1</a-input-search>",
    "a-input-number:default-value": "<a-input-number :default-value=\"$1\">$2</a-input-number>",
    "a-date-picker": "<a-date-picker>$1</a-date-picker>",
    "a-range-picker": "<a-range-picker>$1</a-range-picker>",
    "a-select": "<a-select>$1</a-select>",
    "a-select-option": "<a-select-option>$1</a-select-option>",
    "a-input:placeholder": "<a-input placeholder=\"$1\">$2</a-input>",
    "a-auto-complete:placeholder": "<a-auto-complete placeholder=\"$1\">$2</a-auto-complete>",
    "a-time-picker": "<a-time-picker>$1</a-time-picker>",
    "a-cascader": "<a-cascader>$1</a-cascader>",
    "a-time-range-picker": "<a-time-range-picker>$1</a-time-range-picker>",
    "a-tree-select:value": "<a-tree-select value=\"$1\">$2</a-tree-select>",
    "a-dropdown:placement": "<a-dropdown placement=\"$1\">$2</a-dropdown>",
    "a-space-compact:direction": "<a-space-compact direction=\"$1\">$2</a-space-compact>",
    "a-anchor": "<a-anchor>$1</a-anchor>",
    "a-anchor:affix": "<a-anchor :affix=\"$1\">$2</a-anchor>",
    "a-anchor:direction": "<a-anchor direction=\"$1\">$2</a-anchor>",
    "a-anchor:target-offset": "<a-anchor :target-offset=\"$1\">$2</a-anchor>",
    "a-breadcrumb:routes": "<a-breadcrumb :routes=\"$1\">$2</a-breadcrumb>",
    "a-breadcrumb:separator": "<a-breadcrumb separator=\"$1\">$2</a-breadcrumb>",
    "a-breadcrumb-item:href": "<a-breadcrumb-item href=\"$1\">$2</a-breadcrumb-item>",
    "a-breadcrumb-separator": "<a-breadcrumb-separator>$1</a-breadcrumb-separator>",
    "a-dropdown-button": "<a-dropdown-button>$1</a-dropdown-button>",
    "a-menu-divider": "<a-menu-divider>$1</a-menu-divider>",
    "a-dropdown": "<a-dropdown>$1</a-dropdown>",
    "a-dropdown:v-model:open": "<a-dropdown v-model:open=\"$1\">$2</a-dropdown>",
    "a-dropdown-button:type": "<a-dropdown-button type=\"$1\">$2</a-dropdown-button>",
    "a-dropdown-button:loading": "<a-dropdown-button :loading=\"$1\">$2</a-dropdown-button>",
    "a-menu:id": "<a-menu id=\"$1\">$2</a-menu>",
    "a-menu:v-model:openKeys": "<a-menu v-model:openKeys=\"$1\">$2</a-menu>",
    "a-switch:checked-children": "<a-switch checked-children=\"$1\">$2</a-switch>",
    "a-menu:open-keys": "<a-menu :open-keys=\"$1\">$2</a-menu>",
    "a-switch": "<a-switch>$1</a-switch>",
    "a-page-header:title": "<a-page-header title=\"$1\">$2</a-page-header>",
    "a-descriptions:size": "<a-descriptions size=\"$1\">$2</a-descriptions>",
    "a-descriptions-item:label": "<a-descriptions-item label=\"$1\">$2</a-descriptions-item>",
    "a-descriptions-item": "<a-descriptions-item>$1</a-descriptions-item>",
    "a-tag:color": "<a-tag color=\"$1\">$2</a-tag>",
    "a-row:type": "<a-row type=\"$1\">$2</a-row>",
    "a-statistic:title": "<a-statistic title=\"$1\">$2</a-statistic>",
    "a-dropdown:key": "<a-dropdown key=\"$1\">$2</a-dropdown>",
    "a-row:class": "<a-row class=\"$1\">$2</a-row>",
    "a-tab-pane:key": "<a-tab-pane key=\"$1\">$2</a-tab-pane>",
    "a-page-header:ghost": "<a-page-header :ghost=\"$1\">$2</a-page-header>",
    "a-checkbox:v-model:checked": "<a-checkbox v-model:checked=\"$1\">$2</a-checkbox>",
    "a-pagination:v-model:current": "<a-pagination v-model:current=\"$1\">$2</a-pagination>",
    "a-pagination:size": "<a-pagination size=\"$1\">$2</a-pagination>",
    "a-steps:current": "<a-steps :current=\"$1\">$2</a-steps>",
    "a-steps:items": "<a-steps :items=\"$1\">$2</a-steps>",
    "a-steps:direction": "<a-steps direction=\"$1\">$2</a-steps>",
    "a-steps:v-model:current": "<a-steps v-model:current=\"$1\">$2</a-steps>",
    "a-list:data-source": "<a-list :data-source=\"$1\">$2</a-list>",
    "a-list-item-meta": "<a-list-item-meta>$1</a-list-item-meta>",
    "a-avatar": "<a-avatar>$1</a-avatar>",
    "a-steps:type": "<a-steps type=\"$1\">$2</a-steps>",
    "a-auto-complete:v-model:value": "<a-auto-complete v-model:value=\"$1\">$2</a-auto-complete>",
    "a-textarea:class": "<a-textarea class=\"$1\">$2</a-textarea>",
    "a-input-search:size": "<a-input-search size=\"$1\">$2</a-input-search>",
    "a-cascader:v-model:value": "<a-cascader v-model:value=\"$1\">$2</a-cascader>",
    "a-checkbox-group:v-model:value": "<a-checkbox-group v-model:value=\"$1\">$2</a-checkbox-group>",
    "a-checkbox:value": "<a-checkbox value=\"$1\">$2</a-checkbox>",
    "a-date-picker:v-model:value": "<a-date-picker v-model:value=\"$1\">$2</a-date-picker>",
    "a-range-picker:v-model:value": "<a-range-picker v-model:value=\"$1\">$2</a-range-picker>",
    "a-date-picker:presets": "<a-date-picker :presets=\"$1\">$2</a-date-picker>",
    "a-range-picker:presets": "<a-range-picker :presets=\"$1\">$2</a-range-picker>",
    "a-date-picker:size": "<a-date-picker :size=\"$1\">$2</a-date-picker>",
    "a-range-picker:size": "<a-range-picker :size=\"$1\">$2</a-range-picker>",
    "a-date-picker:mode": "<a-date-picker :mode=\"$1\">$2</a-date-picker>",
    "a-range-picker:value": "<a-range-picker :value=\"$1\">$2</a-range-picker>",
    "a-date-picker:picker": "<a-date-picker picker=\"$1\">$2</a-date-picker>",
    "a-date-picker:suffix-icon": "<a-date-picker suffix-icon=\"$1\">$2</a-date-picker>",
    "a-range-picker:suffix-icon": "<a-range-picker suffix-icon=\"$1\">$2</a-range-picker>",
    "a-range-picker:disabled-date": "<a-range-picker :disabled-date=\"$1\">$2</a-range-picker>",
    "a-select:v-model:value": "<a-select v-model:value=\"$1\">$2</a-select>",
    "a-date-picker:status": "<a-date-picker status=\"$1\">$2</a-date-picker>",
    "a-range-picker:status": "<a-range-picker status=\"$1\">$2</a-range-picker>",
    "a-form:model": "<a-form :model=\"$1\">$2</a-form>",
    "a-form-item:label": "<a-form-item label=\"$1\">$2</a-form-item>",
    "a-input:v-model:value": "<a-input v-model:value=\"$1\">$2</a-input>",
    "a-input-password:v-model:value": "<a-input-password v-model:value=\"$1\">$2</a-input-password>",
    "a-form-item:name": "<a-form-item name=\"$1\">$2</a-form-item>",
    "a-form-item": "<a-form-item>$1</a-form-item>",
    "a-textarea:v-model:value": "<a-textarea v-model:value=\"$1\">$2</a-textarea>",
    "a-form:layout": "<a-form layout=\"$1\">$2</a-form>",
    "a-form-item:wrapper-col": "<a-form-item :wrapper-col=\"$1\">$2</a-form-item>",
    "a-checkbox:checked": "<a-checkbox :checked=\"$1\">$2</a-checkbox>",
    "a-form:label-col": "<a-form :label-col=\"$1\">$2</a-form>",
    "a-tree-select:tree-data": "<a-tree-select :tree-data=\"$1\">$2</a-tree-select>",
    "a-cascader:options": "<a-cascader :options=\"$1\">$2</a-cascader>",
    "a-input-number": "<a-input-number>$1</a-input-number>",
    "a-textarea:rows": "<a-textarea :rows=\"$1\">$2</a-textarea>",
    "a-upload": "<a-upload>$1</a-upload>",
    "a-button:disabled": "<a-button :disabled=\"$1\">$2</a-button>",
    "a-form:ref": "<a-form ref=\"$1\">$2</a-form>",
    "a-form-item:ref": "<a-form-item ref=\"$1\">$2</a-form-item>",
    "a-input-number:v-model:value": "<a-input-number v-model:value=\"$1\">$2</a-input-number>",
    "a-form-item:key": "<a-form-item :key=\"$1\">$2</a-form-item>",
    "a-form-item:v-bind": "<a-form-item v-bind=\"$1\">$2</a-form-item>",
    "a-form:name": "<a-form name=\"$1\">$2</a-form>",
    "a-space:key": "<a-space :key=\"$1\">$2</a-space>",
    "a-button:html-type": "<a-button html-type=\"$1\">$2</a-button>",
    "a-modal:v-model:open": "<a-modal v-model:open=\"$1\">$2</a-modal>",
    "a-input-number:min": "<a-input-number :min=\"$1\">$2</a-input-number>",
    "a-checkbox-group": "<a-checkbox-group>$1</a-checkbox-group>",
    "a-rate:v-model:value": "<a-rate v-model:value=\"$1\">$2</a-rate>",
    "a-upload:v-model:fileList": "<a-upload v-model:fileList=\"$1\">$2</a-upload>",
    "a-upload-dragger:v-model:fileList": "<a-upload-dragger v-model:fileList=\"$1\">$2</a-upload-dragger>",
    "a-form:v-bind": "<a-form v-bind=\"$1\">$2</a-form>",
    "a-input:id": "<a-input id=\"$1\">$2</a-input>",
    "a-tree-select": "<a-tree-select>$1</a-tree-select>",
    "a-form-item:validate-status": "<a-form-item validate-status=\"$1\">$2</a-form-item>",
    "a-inputNumber": "<a-inputNumber>$1</a-inputNumber>",
    "a-input-password": "<a-input-password>$1</a-input-password>",
    "a-mentions": "<a-mentions>$1</a-mentions>",
    "a-textarea": "<a-textarea>$1</a-textarea>",
    "a-input:suffix": "<a-input suffix=\"$1\">$2</a-input>",
    "a-input-search:v-model:value": "<a-input-search v-model:value=\"$1\">$2</a-input-search>",
    "a-input-group:size": "<a-input-group size=\"$1\">$2</a-input-group>",
    "a-input-group": "<a-input-group>$1</a-input-group>",
    "a-tooltip:placement": "<a-tooltip placement=\"$1\">$2</a-tooltip>",
    "a-input:status": "<a-input status=\"$1\">$2</a-input>",
    "a-cascader:placeholder": "<a-cascader placeholder=\"$1\">$2</a-cascader>",
    "a-input-number:id": "<a-input-number id=\"$1\">$2</a-input-number>",
    "a-input-number:status": "<a-input-number status=\"$1\">$2</a-input-number>",
    "a-mentions:v-model:value": "<a-mentions v-model:value=\"$1\">$2</a-mentions>",
    "a-radio:v-model:checked": "<a-radio v-model:checked=\"$1\">$2</a-radio>",
    "a-radio:style": "<a-radio :style=\"$1\">$2</a-radio>",
    "a-rate:value": "<a-rate :value=\"$1\">$2</a-rate>",
    "a-select:ref": "<a-select ref=\"$1\">$2</a-select>",
    "a-select-opt-group:label": "<a-select-opt-group label=\"$1\">$2</a-select-opt-group>",
    "a-input:ref": "<a-input ref=\"$1\">$2</a-input>",
    "a-spin:size": "<a-spin size=\"$1\">$2</a-spin>",
    "a-tag:closable": "<a-tag :closable=\"$1\">$2</a-tag>",
    "a-select:status": "<a-select status=\"$1\">$2</a-select>",
    "a-slider:id": "<a-slider id=\"$1\">$2</a-slider>",
    "a-slider:tip-formatter": "<a-slider :tip-formatter=\"$1\">$2</a-slider>",
    "a-time-picker:v-model:value": "<a-time-picker v-model:value=\"$1\">$2</a-time-picker>",
    "a-time-picker:status": "<a-time-picker status=\"$1\">$2</a-time-picker>",
    "a-time-range-picker:status": "<a-time-range-picker status=\"$1\">$2</a-time-range-picker>",
    "a-time-picker:bordered": "<a-time-picker :bordered=\"$1\">$2</a-time-picker>",
    "a-time-range-picker:bordered": "<a-time-range-picker :bordered=\"$1\">$2</a-time-range-picker>",
    "a-time-range-picker:v-model:value": "<a-time-range-picker v-model:value=\"$1\">$2</a-time-range-picker>",
    "a-transfer:v-model:target-keys": "<a-transfer v-model:target-keys=\"$1\">$2</a-transfer>",
    "a-table:data-source": "<a-table :data-source=\"$1\">$2</a-table>",
    "a-tree:tree-data": "<a-tree :tree-data=\"$1\">$2</a-tree>",
    "a-transfer:status": "<a-transfer status=\"$1\">$2</a-transfer>",
    "a-tree-select:v-model:value": "<a-tree-select v-model:value=\"$1\">$2</a-tree-select>",
    "a-tree-select:status": "<a-tree-select status=\"$1\">$2</a-tree-select>",
    "a-upload:v-model:file-list": "<a-upload v-model:file-list=\"$1\">$2</a-upload>",
    "a-upload:multiple": "<a-upload :multiple=\"$1\">$2</a-upload>",
    "a-modal:open": "<a-modal :open=\"$1\">$2</a-modal>",
    "a-upload:file-list": "<a-upload :file-list=\"$1\">$2</a-upload>",
    "a-avatar:size": "<a-avatar :size=\"$1\">$2</a-avatar>",
    "a-avatar:shape": "<a-avatar shape=\"$1\">$2</a-avatar>",
    "a-avatar-group:max-count": "<a-avatar-group :max-count=\"$1\">$2</a-avatar-group>",
    "a-avatar-group:shape": "<a-avatar-group shape=\"$1\">$2</a-avatar-group>",
    "a-badge:count": "<a-badge :count=\"$1\">$2</a-badge>",
    "a-badge": "<a-badge>$1</a-badge>",
    "a-badge:status": "<a-badge status=\"$1\">$2</a-badge>",
    "a-badge-ribbon:text": "<a-badge-ribbon text=\"$1\">$2</a-badge-ribbon>",
    "a-card:size": "<a-card size=\"$1\">$2</a-card>",
    "a-badge:dot": "<a-badge :dot=\"$1\">$2</a-badge>",
    "a-badge:color": "<a-badge :color=\"$1\">$2</a-badge>",
    "a-calendar:v-model:value": "<a-calendar v-model:value=\"$1\">$2</a-calendar>",
    "a-alert": "<a-alert>$1</a-alert>",
    "a-calendar:value": "<a-calendar :value=\"$1\">$2</a-calendar>",
    "a-radio-group:size": "<a-radio-group size=\"$1\">$2</a-radio-group>",
    "a-select:size": "<a-select size=\"$1\">$2</a-select>",
    "a-card": "<a-card>$1</a-card>",
    "a-card-meta": "<a-card-meta>$1</a-card-meta>",
    "a-card:bordered": "<a-card :bordered=\"$1\">$2</a-card>",
    "a-card:loading": "<a-card :loading=\"$1\">$2</a-card>",
    "a-card-grid": "<a-card-grid>$1</a-card-grid>",
    "a-card-grid:hoverable": "<a-card-grid :hoverable=\"$1\">$2</a-card-grid>",
    "a-card:tab-list": "<a-card :tab-list=\"$1\">$2</a-card>",
    "a-carousel:after-change": "<a-carousel :after-change=\"$1\">$2</a-carousel>",
    "a-carousel:dot-position": "<a-carousel :dot-position=\"$1\">$2</a-carousel>",
    "a-carousel:effect": "<a-carousel effect=\"$1\">$2</a-carousel>",
    "a-carousel": "<a-carousel>$1</a-carousel>",
    "a-collapse:v-model:activeKey": "<a-collapse v-model:activeKey=\"$1\">$2</a-collapse>",
    "a-collapse-panel:key": "<a-collapse-panel key=\"$1\">$2</a-collapse-panel>",
    "a-collapse:default-active-key": "<a-collapse default-active-key=\"$1\">$2</a-collapse>",
    "a-collapse:collapsible": "<a-collapse collapsible=\"$1\">$2</a-collapse>",
    "a-list:item-layout": "<a-list item-layout=\"$1\">$2</a-list>",
    "a-comment:author": "<a-comment :author=\"$1\">$2</a-comment>",
    "a-list": "<a-list>$1</a-list>",
    "a-descriptions": "<a-descriptions>$1</a-descriptions>",
    "a-descriptions-item:span": "<a-descriptions-item :span=\"$1\">$2</a-descriptions-item>",
    "a-descriptions:layout": "<a-descriptions layout=\"$1\">$2</a-descriptions>",
    "a-empty": "<a-empty>$1</a-empty>",
    "a-empty:image": "<a-empty :image=\"$1\">$2</a-empty>",
    "a-select:style": "<a-select :style=\"$1\">$2</a-select>",
    "a-tree-select:style": "<a-tree-select :style=\"$1\">$2</a-tree-select>",
    "a-cascader:style": "<a-cascader :style=\"$1\">$2</a-cascader>",
    "a-transfer": "<a-transfer>$1</a-transfer>",
    "a-table:columns": "<a-table :columns=\"$1\">$2</a-table>",
    "a-empty:description": "<a-empty :description=\"$1\">$2</a-empty>",
    "a-image:width": "<a-image :width=\"$1\">$2</a-image>",
    "a-image-preview-group": "<a-image-preview-group>$1</a-image-preview-group>",
    "a-image": "<a-image>$1</a-image>",
    "a-list:size": "<a-list size=\"$1\">$2</a-list>",
    "a-list:loading": "<a-list :loading=\"$1\">$2</a-list>",
    "a-skeleton:title": "<a-skeleton :title=\"$1\">$2</a-skeleton>",
    "a-avatar:src": "<a-avatar :src=\"$1\">$2</a-avatar>",
    "a-list-item:key": "<a-list-item key=\"$1\">$2</a-list-item>",
    "a-list-item-meta:description": "<a-list-item-meta :description=\"$1\">$2</a-list-item-meta>",
    "a-popover:title": "<a-popover title=\"$1\">$2</a-popover>",
    "a-popover:placement": "<a-popover placement=\"$1\">$2</a-popover>",
    "a-popover:v-model:open": "<a-popover v-model:open=\"$1\">$2</a-popover>",
    "a-popover:trigger": "<a-popover trigger=\"$1\">$2</a-popover>",
    "a-qrcode:value": "<a-qrcode :value=\"$1\">$2</a-qrcode>",
    "a-qrcode:status": "<a-qrcode status=\"$1\">$2</a-qrcode>",
    "a-qrcode:size": "<a-qrcode :size=\"$1\">$2</a-qrcode>",
    "a-qrcode:ref": "<a-qrcode ref=\"$1\">$2</a-qrcode>",
    "a-popover": "<a-popover>$1</a-popover>",
    "a-qrcode:bordered": "<a-qrcode :bordered=\"$1\">$2</a-qrcode>",
    "a-qrcode:error-level": "<a-qrcode error-level=\"$1\">$2</a-qrcode>",
    "a-qrcode:type": "<a-qrcode type=\"$1\">$2</a-qrcode>",
    "a-qrcode:color": "<a-qrcode :color=\"$1\">$2</a-qrcode>",
    "a-statistic:value": "<a-statistic :value=\"$1\">$2</a-statistic>",
    "a-statistic:precision": "<a-statistic :precision=\"$1\">$2</a-statistic>",
    "a-statistic-countdown:value": "<a-statistic-countdown :value=\"$1\">$2</a-statistic-countdown>",
    "a-statistic-countdown:title": "<a-statistic-countdown title=\"$1\">$2</a-statistic-countdown>",
    "a-popconfirm": "<a-popconfirm>$1</a-popconfirm>",
    "a-table:row-selection": "<a-table :row-selection=\"$1\">$2</a-table>",
    "a-table-summary": "<a-table-summary>$1</a-table-summary>",
    "a-table-summary-cell:index": "<a-table-summary-cell :index=\"$1\">$2</a-table-summary-cell>",
    "a-table:size": "<a-table size=\"$1\">$2</a-table>",
    "a-table-summary-cell:col-span": "<a-table-summary-cell :col-span=\"$1\">$2</a-table-summary-cell>",
    "a-table-column:key": "<a-table-column key=\"$1\">$2</a-table-column>",
    "a-tabs:v-model:activeKey": "<a-tabs v-model:activeKey=\"$1\">$2</a-tabs>",
    "a-tag": "<a-tag>$1</a-tag>",
    "a-checkable-tag": "<a-checkable-tag>$1</a-checkable-tag>",
    "a-checkable-tag:key": "<a-checkable-tag :key=\"$1\">$2</a-checkable-tag>",
    "a-tag:bordered": "<a-tag :bordered=\"$1\">$2</a-tag>",
    "a-timeline:pending": "<a-timeline pending=\"$1\">$2</a-timeline>",
    "a-timeline:mode": "<a-timeline mode=\"$1\">$2</a-timeline>",
    "a-timeline-item:color": "<a-timeline-item color=\"$1\">$2</a-timeline-item>",
    "a-timeline-item": "<a-timeline-item>$1</a-timeline-item>",
    "a-tooltip:key": "<a-tooltip :key=\"$1\">$2</a-tooltip>",
    "a-button:ref": "<a-button ref=\"$1\">$2</a-button>",
    "a-tour:v-model:current": "<a-tour v-model:current=\"$1\">$2</a-tour>",
    "a-tour:open": "<a-tour :open=\"$1\">$2</a-tour>",
    "a-tree:v-model:expandedKeys": "<a-tree v-model:expandedKeys=\"$1\">$2</a-tree>",
    "a-tree:expanded-keys": "<a-tree :expanded-keys=\"$1\">$2</a-tree>",
    "a-directory-tree:v-model:expandedKeys": "<a-directory-tree v-model:expandedKeys=\"$1\">$2</a-directory-tree>",
    "a-tree:v-model:selectedKeys": "<a-tree v-model:selectedKeys=\"$1\">$2</a-tree>",
    "a-tree:show-line": "<a-tree :show-line=\"$1\">$2</a-tree>",
    "a-alert:type": "<a-alert type=\"$1\">$2</a-alert>",
    "a-alert:message": "<a-alert message=\"$1\">$2</a-alert>",
    "a-alert:show-icon": "<a-alert :show-icon=\"$1\">$2</a-alert>",
    "a-drawer:v-model:open": "<a-drawer v-model:open=\"$1\">$2</a-drawer>",
    "a-drawer:placement": "<a-drawer :placement=\"$1\">$2</a-drawer>",
    "a-drawer:width": "<a-drawer :width=\"$1\">$2</a-drawer>",
    "a-list-item": "<a-list-item>$1</a-list-item>",
    "a-drawer:size": "<a-drawer :size=\"$1\">$2</a-drawer>",
    "a-modal:ref": "<a-modal ref=\"$1\">$2</a-modal>",
    "a-popconfirm:open": "<a-popconfirm :open=\"$1\">$2</a-popconfirm>",
    "a-popconfirm:placement": "<a-popconfirm placement=\"$1\">$2</a-popconfirm>",
    "a-popconfirm:title": "<a-popconfirm title=\"$1\">$2</a-popconfirm>",
    "a-progress:percent": "<a-progress :percent=\"$1\">$2</a-progress>",
    "a-progress:type": "<a-progress type=\"$1\">$2</a-progress>",
    "a-progress:stroke-linecap": "<a-progress stroke-linecap=\"$1\">$2</a-progress>",
    "a-progress:steps": "<a-progress :steps=\"$1\">$2</a-progress>",
    "a-result:status": "<a-result status=\"$1\">$2</a-result>",
    "a-result": "<a-result>$1</a-result>",
    "a-skeleton": "<a-skeleton>$1</a-skeleton>",
    "a-skeleton:loading": "<a-skeleton :loading=\"$1\">$2</a-skeleton>",
    "a-skeleton-button:active": "<a-skeleton-button :active=\"$1\">$2</a-skeleton-button>",
    "a-skeleton-avatar:active": "<a-skeleton-avatar :active=\"$1\">$2</a-skeleton-avatar>",
    "a-skeleton-input:active": "<a-skeleton-input :active=\"$1\">$2</a-skeleton-input>",
    "a-skeleton-image": "<a-skeleton-image>$1</a-skeleton-image>",
    "a-spin": "<a-spin>$1</a-spin>",
    "a-spin:tip": "<a-spin tip=\"$1\">$2</a-spin>",
    "a-spin:indicator": "<a-spin :indicator=\"$1\">$2</a-spin>",
    "a-spin:spinning": "<a-spin :spinning=\"$1\">$2</a-spin>",
    "a-affix:offset-top": "<a-affix :offset-top=\"$1\">$2</a-affix>",
    "a-affix:offset-bottom": "<a-affix :offset-bottom=\"$1\">$2</a-affix>",
    "a-affix": "<a-affix>$1</a-affix>",
    "a-radio-button:key": "<a-radio-button key=\"$1\">$2</a-radio-button>",
    "a-config-provider": "<a-config-provider>$1</a-config-provider>",
    "a-pagination:total": "<a-pagination :total=\"$1\">$2</a-pagination>",
    "a-calendar:fullscreen": "<a-calendar :fullscreen=\"$1\">$2</a-calendar>",
    "a-config-provider:component-size": "<a-config-provider :component-size=\"$1\">$2</a-config-provider>",
    "a-datePicker": "<a-datePicker>$1</a-datePicker>",
    "a-config-provider:direction": "<a-config-provider :direction=\"$1\">$2</a-config-provider>",
    "a-switch:size": "<a-switch size=\"$1\">$2</a-switch>",
    "a-radio-group:default-value": "<a-radio-group default-value=\"$1\">$2</a-radio-group>",
    "a-input-search:enter-button": "<a-input-search enter-button=\"$1\">$2</a-input-search>",
    "a-select:option-filter-prop": "<a-select option-filter-prop=\"$1\">$2</a-select>",
    "a-switch:checked": "<a-switch :checked=\"$1\">$2</a-switch>",
    "a-pagination:default-current": "<a-pagination :default-current=\"$1\">$2</a-pagination>",
    "a-float-button": "<a-float-button>$1</a-float-button>",
    "a-float-button:shape": "<a-float-button shape=\"$1\">$2</a-float-button>",
    "a-float-button-group:trigger": "<a-float-button-group trigger=\"$1\">$2</a-float-button-group>",
    "a-float-button-group:shape": "<a-float-button-group shape=\"$1\">$2</a-float-button-group>",
    "a-back-top:visibility-height": "<a-back-top :visibility-height=\"$1\">$2</a-back-top>",
    "a-float-button:type": "<a-float-button type=\"$1\">$2</a-float-button>",
    "a-back-top": "<a-back-top>$1</a-back-top>",
    "a-watermark": "<a-watermark>$1</a-watermark>",
    "a-watermark:height": "<a-watermark :height=\"$1\">$2</a-watermark>",
    "a-watermark:v-bind": "<a-watermark v-bind=\"$1\">$2</a-watermark>",
    "a-input-number:placeholder": "<a-input-number placeholder=\"$1\">$2</a-input-number>"
}