export default {
  "Row/gutter": {"description": "栅格间距，单位 px，左右平分。默认值：0，类型：Number。"},
  "Row/type": {options: ["flex"], "description": "布局模式，可选值为flex或不选，在现代浏览器下有效"},
  "Row/align": {options: ["top", "middle", "bottom"], "description": "flex 布局下的垂直对齐方式，可选值为top、middle、bottom"},
  "Row/justify": {options: ["start", "end", "center", "space-around", "space-between"],"description": "flex 布局下的水平排列方式，可选值为start、end、center、space-around、space-between"},
  "Row/class-name": {"description": "自定义的class名称"},
  "Col/span": {"description": "栅格的占位格数，可选值为0~24的整数，为 0 时，相当于display:none，类型： Number|String"},
  "Sider/breakpoint": {"options": ["xs", "sm", "md", "lg", "xl", "xxl"], "description": "触发响应式布局的断点，若不设此属性则不会触发响应式布局。"},
  "Sider/value": {type: "boolean", "description": "侧边栏是否收起"},
  "Sider/width": {"description": "宽度，类型Number，默认值 200"},
  "Sider/collapsible": {type: "boolean", "description": "是否可收起，设为false后，默认触发器会隐藏，且响应式布局不会触发"},
  "Sider/collapsed-width":  {"description": "收缩宽度，设置为 0 会出现特殊 trigger， 类型number， 默认值 64"},
  "Sider/hide-trigger": {type: "boolean", "description": "隐藏默认触发器"},
  "Sider/default-collapsed": {type: "boolean", "description": "是否默认收起，设置了collapsible后设置此属性侧边栏仍会收起。"},
  "Sider/reverse-arrow": {type: "boolean", "description": "改变侧边栏触发器箭头方向，和改变侧边栏收起方向，当Sider在右边时可以使用。"},
  "Sider/on-collapse":  {type: "method", "description": "展开-收起时的回调"},
  "Sider/toggleCollapse":  {type: "method", "description": "改变Sider展开-收起状态。"},
  "Button/type": {"options": ["primary", "ghost", "dashed", "text", "info", "success", "warning", "error"], "description": "按钮类型"},
  "Button/size": {"options": ["large", "small", "default"], "description": "按钮大小"},
  "Button/shape": {"options": ["circle"], "description": "按钮形状"},
  "Button/long": {type: "boolean", "description": "开启后，按钮的长度为 100%"},
  "Button/html-type": {"options": ["button", "submit", "reset"], "description": "设置button原生的type，可选值为button、submit、reset"},
  "Button/disabled": {type: "boolean", "description": "设置按钮为禁用状态"},
  "Button/loading": {type: "boolean", "description": "设置按钮为加载中状态"},
  "Button/icon": {"description": "设置按钮的图标类型"},
  "ButtonGroup/size": {"options": ["large", "small", "default"], "description": "按钮组大小"},
  "ButtonGroup/shape": {"options": ["circle"], "description": "按钮组形状"},
  "ButtonGroup/vertical": {type: "boolean", "description": "是否纵向排列按钮组"},
  "Input/type": {"options": ["text", "password", "textarea", "url", "email", "date"], "description": "输入框类型"},
  "Input/value": {"description": "绑定的值，可使用 v-model 双向绑定"},
  "Input/size": {"options": ["large", "small", "default"], "description": "输入框尺寸"},
  "Input/placeholder": {"description": "占位文本"},
  "Input/clearable": {type: "boolean", "description": "是否显示清空按钮"},
  "Input/disabled": {type: "boolean", "description": "设置输入框为禁用状态"},
  "Input/readonly": {type: "boolean", "description": "设置输入框为只读"},
  "Input/maxlength": {"description": "最大输入长度，类型Number"},
  "Input/icon": {"description": "输入框尾部图标，仅在 text 类型下有效"},
  "Input/rows": {"description": "文本域默认行数，仅在 textarea 类型下有效，类型Number，默认值：2"},
  "Input/autosize": {type: "boolean", "description": "自适应内容高度，仅在 textarea 类型下有效，可传入对象，如 { minRows: 2, maxRows: 6 }"},
  "Input/number": {type: "boolean", "description": "将用户的输入转换为 Number 类型"},
  "Input/autofocus": {type: "boolean", "description": "自动获取焦点"},
  "Input/autocomplete":  {"options": ["off", "on"], "description": "原生的自动完成功能，默认off"},
  "Input/element-id":  {"description": "给表单元素设置 id"},
  "Input/spellcheck": {type: "boolean", "description": "原生的 spellcheck 属性"},
  "Input/wrap": {"options": ["hard", "soft"], "description": "原生的 wrap 属性"},
  "Input/on-enter": {type: "method", "description": "按下回车键时触发"},
  "Input/on-click": {type: "method", "description": "按下回车键时触发"},
  "Input/on-change": {type: "method", "description": "按下回车键时触发"},
  "Input/on-focus": {type: "method", "description": "按下回车键时触发"},
  "Input/on-blur": {type: "method", "description": "按下回车键时触发"},
  "Input/on-keyup": {type: "method", "description": "按下回车键时触发"},
  "Input/on-keydown": {type: "method", "description": "按下回车键时触发"},
  "Input/on-keypress": {type: "method", "description": "按下回车键时触发"},
  "Input/focus": {type: "method", "description": "手动聚焦输入框"},
  "Radio/value": { "description": "只在单独使用时有效。可以使用 v-model 双向绑定数据", "type": "boolean" }, 
  "Radio/label ": { "description": "只在组合使用时有效。指定当前选项的 value 值，组合会自动判断当前选择的项目" }, 
  "Radio/disabled": { "description": "是否禁用当前项", "type": "boolean" }, 
  "Radio/size": { "description": "单选框的尺寸，可选值为 large、small、default 或者不设置", "options": ["large", "small", "default"]}, 
  "Radio/true-value": { "description": "选中时的值，当使用类似 1 和 0 来判断是否选中时会很有用" }, 
  "Radio/false-value": { "description": "没有选中时的值，当使用类似 1 和 0 来判断是否选中时会很有用" }, 
  "Radio/on-change": { "type": "method", "description": "在选项状态发生改变时触发，返回当前状态。通过修改外部的数据改变时不会触发" }, 
  "RadioGroup/value": { "description": "指定当前选中的项目数据。可以使用 v-model 双向绑定数据" }, 
  "RadioGroup/type": { "description": "可选值为 button 或不填，为 button 时使用按钮样式" }, 
  "RadioGroup/size": { "description": "尺寸，可选值为large、small、default或者不设置" }, 
  "RadioGroup/vertical": { "description": "是否垂直排列，按钮样式下无效", "type": "boolean" }, 
  "RadioGroup/on-change": { "type": "method", "description": "在选项状态发生改变时触发，返回当前选中的项。通过修改外部的数据改变时不会触发" },
  "Checkbox/value": { "description": "只在单独使用时有效。可以使用 v-model 双向绑定数据", "type": "boolean" }, 
  "Checkbox/label": { "description": "只在组合使用时有效。指定当前选项的 value 值，组合会自动判断是否选中" }, 
  "Checkbox/disabled": { "description": "是否禁用当前项", "type": "boolean" }, 
  "Checkbox/indeterminate": { "description": "设置 indeterminate 状态，只负责样式控制", "type": "boolean" }, 
  "Checkbox/size": { "description": "多选框的尺寸，可选值为 large、small、default 或者不设置", "options": ["large", "small", "default"]}, 
  "Checkbox/true-value": { "description": "选中时的值，当使用类似 1 和 0 来判断是否选中时会很有用" }, 
  "Checkbox/false-value": { "description": "没有选中时的值，当使用类似 1 和 0 来判断是否选中时会很有用" }, 
  "Checkbox/on-change": { "type": "method", "description": "只在单独使用时有效。在选项状态发生改变时触发，通过修改外部的数据改变时不会触发" }, 
  "CheckboxGroup/value": { "description": "指定选中项目的集合，可以使用 v-model 双向绑定数据" }, 
  "CheckboxGroup/size": { "description": "多选框组的尺寸，可选值为 large、small、default 或者不设置", "options": ["large", "small", "default"]}, 
  "CheckboxGroup/on-change": { "type": "method", "description": "在选项状态发生改变时触发，返回已选中的数组。通过修改外部的数据改变时不会触发" },
  "Switch/value": { "description": "指定当前是否选中，可以使用 v-model 双向绑定数据", "type": "boolean" }, 
  "Switch/size": { "description": "开关的尺寸，可选值为large、small、default或者不写。建议开关如果使用了2个汉字的文字，使用 large。", "options": ["large", "small", "default"]}, 
  "Switch/disabled": { "description": "禁用开关", "type": "boolean" }, 
  "Switch/true-value": { "description": "选中时的值，当使用类似 1 和 0 来判断是否选中时会很有用" }, 
  "Switch/false-value": { "description": "没有选中时的值，当使用类似 1 和 0 来判断是否选中时会很有用" }, 
  "Switch/on-change": { "type": "method", "description": "开关变化时触发，返回当前的状态" },
  "Table/data": { "description": "显示的结构化数据，其中，字段 cellClassName 用于设置任意单元格的样式名称，因此数据不能使用该字段，详见示例特定样式。" }, 
  "Table/columns": { "description": "表格列的配置描述，具体项见后文" }, 
  "Table/stripe": { "description": "是否显示间隔斑马纹", "type": "boolean" }, 
  "Table/border": { "description": "是否显示纵向边框", "type": "boolean" }, 
  "Table/show-header": { "description": "是否显示表头", "type": "boolean" }, 
  "Table/width": { "description": "表格宽度，单位 px" }, 
  "Table/height": { "description": "表格高度，单位 px，设置后，如果表格内容大于此值，会固定表头" }, 
  "Table/loading": { "description": "表格是否加载中", "type": "boolean" }, 
  "Table/disabled-hover": { "description": "禁用鼠标悬停时的高亮", "type": "boolean" }, 
  "Table/highlight-row": { "description": "是否支持高亮选中的行，即单选", "type": "boolean" }, 
  "Table/row-class-name": { "description": "行的 className 的回调方法，传入参数：row：当前行数据 index：当前行的索引" }, 
  "Table/size": { "description": "表格尺寸，可选值为 large、small、default 或者不填", "options": ["large", "small", "default"]}, 
  "Table/no-data-text": { "description": "数据为空时显示的提示内容" }, 
  "Table/no-filtered-data-text": { "description": "筛选数据为空时显示的提示内容" }, 
  "Table/on-current-change": { "type": "method", "description": "开启 highlight-row 后有效，当表格的当前行发生变化的时候会触发" }, 
  "Table/on-select": { "type": "method", "description": "在多选模式下有效，选中某一项时触发" }, 
  "Table/on-select-cancel": { "type": "method", "description": "在多选模式下有效，取消选中某一项时触发" }, 
  "Table/on-select-all": { "type": "method", "description": "在多选模式下有效，点击全选时触发" }, 
  "Table/on-selection-change": { "type": "method", "description": "在多选模式下有效，只要选中项发生变化时就会触发" }, 
  "Table/on-sort-change": { "type": "method", "description": "排序时有效，当点击排序时触发" }, 
  "Table/on-filter-change": { "type": "method", "description": "筛选时有效，筛选条件发生变化时触发" }, 
  "Table/on-row-click": { "type": "method", "description": "单击某一行时触发" }, 
  "Table/on-row-dblclick": { "type": "method", "description": "双击某一行时触发" }, 
  "Table/on-expand": { "type": "method", "description": "展开或收起某一行时触发" }, 
  "Table/exportCsv": { "type": "method", "description": "将数据导出为 .csv 文件，说明：支持IE9~IE11、Edge、Chrome、Safari、Firefox 全系列浏览器。 IE9、Safari 需要手动修改后缀名为 .csv。 IE9暂时只支持英文，中文会显示为乱码。" }, 
  "Table/clearCurrentRow": { "type": "method", "description": "清除高亮项，仅在开启 highlight-row 时可用" },
  "Select/value": { "description": "指定选中项目的 value 值，可以使用 v-model 双向绑定数据。单选时只接受 String 或 Number，多选时只接受 Array" }, 
  "Select/multiple": { "description": "是否支持多选", "type": "boolean" }, 
  "Select/disabled": { "description": "是否禁用", "type": "boolean" }, 
  "Select/clearable": { "description": "是否可以清空选项，只在单选时有效", "type": "boolean" }, 
  "Select/filterable": { "description": "是否支持搜索", "type": "boolean" }, 
  "Select/remote": { "description": "是否使用远程搜索", "type": "boolean" }, 
  "Select/remote-method": { "description": "远程搜索的方法" }, 
  "Select/loading": { "description": "当前是否正在远程搜索", "type": "boolean" }, 
  "Select/loading-text": { "description": "远程搜索中的文字提示" }, 
  "Select/label": { "description": "仅在 remote 模式下，初始化时使用。因为仅通过 value 无法得知选项的 label，需手动设置。" }, 
  "Select/size": { "description": "选择框大小，可选值为large、small、default或者不填", "options": ["large", "small", "default"]}, 
  "Select/placeholder": { "description": "选择框默认文字" }, 
  "Select/not-found-text": { "description": "当下拉列表为空时显示的内容" }, 
  "Select/label-in-value": { "description": "在返回选项时，是否将 label 和 value 一并返回，默认只返回 value", "type": "boolean" }, 
  "Select/placement": { "description": "弹窗的展开方向，可选值为 bottom 和 top，2.12.0 版本开始支持自动识别" }, 
  "Select/transfer": { "description": "是否将弹层放置于 body 内，在 Tabs、带有 fixed 的 Table 列内使用时，建议添加此属性，它将不受父级样式影响，从而达到更好的效果", "type": "boolean" }, 
  "Select/element-id": { "description": "给表单元素设置 id，详见 Form 用法。" }, 
  "Select/on-change": { "type": "method", "description": "选中的Option变化时触发，默认返回 value，如需返回 label，详见 label-in-value 属性" }, 
  "Select/on-query-change": { "type": "method", "description": "搜索词改变时触发" }, 
  "Select/on-clear": { "type": "method", "description": "点击清空按钮时触发" }, 
  "Select/on-open-change": { "type": "method", "description": "下拉框展开或收起时触发" }, 
  "Select/setQuery": { "type": "method", "description": "设置搜索词，为空时清空，仅在 filterable=\"true\" 时有效" }, 
  "Select/clearSingleSelect": { "type": "method", "description": "清空单选项，仅在 clearable=\"true\" 时有效" }, 
  "Option/value": { "description": "选项值，默认根据此属性值进行筛选，必填" }, 
  "Option/label": { "description": "选项显示的内容，默认会读取 slot，无 slot 时，优先读取该 label 值，无 label 时，读取 value。当选中时，选择器会显示 label 为已选文案。大部分情况不需要配置此项，直接写入 slot 即可，在自定义选项时，该属性非常有用。" }, 
  "Option/disabled": { "description": "是否禁用当前项", "type": "boolean" }, 
  "OptionGroup/label": { "description": "分组的组名" },
  "AutoComplete/value": { "description": "绑定的值，可使用 v-model 双向绑定" }, 
  "AutoComplete/data": { "description": "自动完成的数据源" }, 
  "AutoComplete/clearable": { "description": "是否可以清空选项", "type": "boolean" }, 
  "AutoComplete/disabled": { "description": "是否禁用", "type": "boolean" }, 
  "AutoComplete/placeholder": { "description": "占位文本" }, 
  "AutoComplete/size": { "description": "输入框尺寸，可选值为 large、small、default 或者不设置", "options": ["large", "small", "default"]}, 
  "AutoComplete/icon": { "description": "输入框尾部图标" }, 
  "AutoComplete/filter-method": { "description": "是否根据输入项进行筛选。当其为一个函数时，会接收 value 和 option 两个参数，当 option 符合筛选条件时，应返回 true，反之则返回 false" }, 
  "AutoComplete/placement": { "description": "弹窗的展开方向，可选值为 bottom 和 top，2.12.0 版本开始支持自动识别" }, 
  "AutoComplete/transfer": { "description": "是否将弹层放置于 body 内，在 Tabs、带有 fixed 的 Table 列内使用时，建议添加此属性，它将不受父级样式影响，从而达到更好的效果", "type": "boolean" }, 
  "AutoComplete/element-id": { "description": "给表单元素设置 id，详见 Form 用法。" }, 
  "AutoComplete/on-change": { "type": "method", "description": "选中 option，或 input 的 value 变化时，调用此函数" }, 
  "AutoComplete/on-select": { "type": "method", "description": "被选中时调用，参数为选中项的 value 值" }, 
  "AutoComplete/on-search": { "type": "method", "description": "搜索补全项的时候调用" }, 
  "AutoComplete/on-focus": { "type": "method", "description": "聚焦时触发" }, 
  "AutoComplete/on-blur": { "type": "method", "description": "失焦时触发" },
  "Slider/value": { "description": "滑块选定的值，可以使用 v-model 双向绑定数据。普通模式下，数据格式为数字，在双滑块模式下，数据格式为长度是2的数组，且每项都为数字" }, 
  "Slider/min": { "description": "最小值" }, 
  "Slider/max": { "description": "最大值" }, 
  "Slider/step": { "description": "步长，取值建议能被（max - min）整除" }, 
  "Slider/disabled": { "description": "是否禁用滑块", "type": "boolean" }, 
  "Slider/range": { "description": "是否开启双滑块模式", "type": "boolean" }, 
  "Slider/show-input": { "description": "是否显示数字输入框，仅在单滑块模式下有效", "type": "boolean" }, 
  "Slider/show-stops": { "description": "是否显示间断点，建议在 step 不密集时使用", "type": "boolean" }, 
  "Slider/show-tip": { "description": "提示的显示控制，可选值为 hover（悬停，默认）、always（总是可见）、never（不可见）" }, 
  "Slider/tip-format": { "description": "Slider 会把当前值传给 tip-format，并在 Tooltip 中显示 tip-format 的返回值，若为 null，则隐藏 Tooltip" }, 
  "Slider/input-size": { "description": "数字输入框的尺寸，可选值为large、small、default或者不填，仅在开启 show-input 时有效", "options": ["large", "small", "default"]}, 
  "Slider/on-change": { "type": "method", "description": "在松开滑动时触发，返回当前的选值，在滑动过程中不会触发" }, 
  "Slider/on-input": { "type": "method", "description": "滑动条数据变化时触发，返回当前的选值，在滑动过程中实时触发" },
  "DatePicker/type": { "description": "显示类型，可选值为 date、daterange、datetime、datetimerange、year、month", "options": ["date", "daterange", "datetime", "datetimerange", "year", "month"]}, 
  "DatePicker/value": { "description": "日期，可以是 JavaScript 的 Date，例如 new Date()，也可以是标准的日期格式，点击右边查看注意：value 使用 v-model 时，值是 Date 类型，可以配合 @on-change 使用" }, 
  "DatePicker/format": { "description": "展示的日期格式" }, 
  "DatePicker/placement": { "description": "日期选择器出现的位置，2.12.0 版本开始支持自动识别", 
    "options": ["top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end", "left", "left-start", "left-end", "right", "right-start", "right-end"]}, 
  "DatePicker/placeholder": { "description": "占位文本" }, 
  "DatePicker/options": { "description": "选择器额外配置，比如不可选日期与快捷选项，具体项详见下表" }, 
  "DatePicker/split-panels": { "description": "开启后，左右面板不联动，仅在 daterange 和 datetimerange 下可用。", "type": "boolean" }, 
  "DatePicker/multiple": { "description": "开启后，可以选择多个日期，仅在 date 下可用。", "type": "boolean" }, 
  "DatePicker/show-week-numbers": { "description": "开启后，可以显示星期数。", "type": "boolean" }, 
  "DatePicker/start-date": { "description": "设置默认显示的起始日期。" }, 
  "DatePicker/confirm": { "description": "是否显示底部控制栏，开启后，选择完日期，选择器不会主动关闭，需用户确认后才可关闭", "type": "boolean" }, 
  "DatePicker/open": { "description": "手动控制日期选择器的显示状态，true 为显示，false 为收起。使用该属性后，选择器不会主动关闭。建议配合 slot 及 confirm 和相关事件一起使用", "type": "boolean" }, 
  "DatePicker/size": { "description": "尺寸，可选值为large、small、default或者不设置", "options": ["large", "small", "default"]}, 
  "DatePicker/disabled": { "description": "是否禁用选择器", "type": "boolean" }, 
  "DatePicker/clearable": { "description": "是否显示清除按钮", "type": "boolean" }, 
  "DatePicker/readonly": { "description": "完全只读，开启后不会弹出选择器，只在没有设置 open 属性下生效", "type": "boolean" }, 
  "DatePicker/editable": { "description": "文本框是否可以输入，只在没有使用 slot 时有效", "type": "boolean" }, 
  "DatePicker/transfer": { "description": "是否将弹层放置于 body 内，在 Tabs、带有 fixed 的 Table 列内使用时，建议添加此属性，它将不受父级样式影响，从而达到更好的效果", "type": "boolean" }, 
  "DatePicker/element-id": { "description": "给表单元素设置 id，详见 Form 用法。" },
  "DatePicker/time-picker-options": { "description": "可以在 type 为 datetime 和 datetimerange 下，配置 TimePicker 的属性，比如时间间隔 steps：:time-picker-options=\"{steps: [1, 10, 10]}\"" }, 
  "DatePicker/on-change": { "type": "method", "description": "日期发生变化时触发" }, 
  "DatePicker/on-open-change": { "type": "method", "description": "弹出日历和关闭日历时触发" }, 
  "DatePicker/on-ok": { "type": "method", "description": "在 confirm 模式下有效，点击确定按钮时触发" }, 
  "DatePicker/on-clear": { "type": "method", "description": "在 confirm 模式或 clearable = true 时有效，在清空日期时触发" },
  "TimePicker/type": { "description": "显示类型，可选值为 time、timerange", "options": ["time", "timerange"]}, 
  "TimePicker/value": { "description": "时间，可以是 JavaScript 的 Date，例如 new Date()，也可以是标准的时间格式，点击右边查看 注意：value 使用 v-model 时，值是 Date 类型，可以配合 @on-change 使用" }, 
  "TimePicker/format": { "description": "展示的时间格式" }, 
  "TimePicker/steps": { "description": "下拉列表的时间间隔，数组的三项分别对应小时、分钟、秒。例如设置为 [1, 15] 时，分钟会显示：00、15、30、45。"}, 
  "TimePicker/placement": { "description": "时间选择器出现的位置, 2.12.0 版本开始支持自动识别", "options": ["top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end", "left", "left-start", "left-end", "right", "right-start", "right-end"]}, 
  "TimePicker/placeholder": { "description": "占位文本" }, 
  "TimePicker/confirm": { "description": "是否显示底部控制栏", "type": "boolean" }, 
  "TimePicker/open": { "description": "手动控制时间选择器的显示状态，true 为显示，false 为收起。使用该属性后，选择器不会主动关闭。建议配合 slot 及 confirm 和相关事件一起使用", "type": "boolean" }, 
  "TimePicker/size": { "description": "尺寸，可选值为large、small、default或者不设置", "options": ["large", "small", "default"]}, 
  "TimePicker/disabled": { "description": "是否禁用选择器", "type": "boolean" }, 
  "TimePicker/clearable": { "description": "是否显示清除按钮", "type": "boolean" }, 
  "TimePicker/readonly": { "description": "完全只读，开启后不会弹出选择器，只在没有设置 open 属性下生效", "type": "boolean" }, 
  "TimePicker/editable": { "description": "文本框是否可以输入，只在没有使用 slot 时有效", "type": "boolean" }, 
  "TimePicker/transfer": { "description": "是否将弹层放置于 body 内，在 Tabs、带有 fixed 的 Table 列内使用时，建议添加此属性，它将不受父级样式影响，从而达到更好的效果", "type": "boolean" }, 
  "TimePicker/element-id": { "description": "给表单元素设置 id，详见 Form 用法。" }, 
  "TimePicker/on-change": { "type": "method", "description": "时间发生变化时触发" }, 
  "TimePicker/on-open-change": { "type": "method", "description": "弹出浮层和关闭浮层时触发" }, 
  "TimePicker/on-ok": { "type": "method", "description": "点击确定按钮时触发" }, 
  "TimePicker/on-clear": { "type": "method", "description": "在清空日期时触发" },
  "Cascader/data": { "description": "可选项的数据源，格式参照示例说明" }, 
  "Cascader/value": { "description": "当前已选项的数据，格式参照示例说明" }, 
  "Cascader/render-format": { "description": "选择后展示的函数，用于自定义显示格式" }, 
  "Cascader/disabled": { "description": "是否禁用选择器", "type": "boolean" }, 
  "Cascader/clearable": { "description": "是否支持清除", "type": "boolean" }, 
  "Cascader/placeholder": { "description": "输入框占位符" }, 
  "Cascader/trigger": { "description": "次级菜单展开方式，可选值为 click 或 hover", "options": ["click", "hover"]}, 
  "Cascader/change-on-select": { "description": "当此项为 true 时，点选每级菜单选项值都会发生变化，具体见上面的示例", "type": "boolean" }, 
  "Cascader/size": { "description": "输入框大小，可选值为large和small或者不填" }, 
  "Cascader/load-data": { "description": "动态获取数据，数据源需标识 loading" }, 
  "Cascader/filterable": { "description": "是否支持搜索", "type": "boolean" }, 
  "Cascader/not-found-text": { "description": "当搜索列表为空时显示的内容" }, 
  "Cascader/transfer": { "description": "是否将弹层放置于 body 内，在 Tabs、带有 fixed 的 Table 列内使用时，建议添加此属性，它将不受父级样式影响，从而达到更好的效果", "type": "boolean" }, 
  "Cascader/element-id": { "description": "给表单元素设置 id，详见 Form 用法。" }, 
  "Cascader/on-change": { "type": "method", "description": "选择完成后的回调，返回值 value 即已选值 value，selectedData 为已选项的具体数据" }, 
  "Cascader/on-visible-change": { "type": "method", "description": "展开和关闭弹窗时触发" },
  "Transfer/data": { "description": "数据源，其中的数据将会被渲染到左边一栏中，targetKeys 中指定的除外。" }, 
  "Transfer/targetKeys": { "description": "显示在右侧框数据的key集合" }, 
  "Transfer/render-format": { "description": "每行数据渲染函数，该函数的入参为 data 中的项" }, 
  "Transfer/selected-keys": { "description": "设置哪些项应该被选中" }, 
  "Transfer/list-style": { "description": "两个穿梭框的自定义样式" }, 
  "Transfer/titles": { "description": "标题集合，顺序从左至右" }, 
  "Transfer/operations": { "description": "操作文案集合，顺序从上至下" }, 
  "Transfer/filterable": { "description": "是否显示搜索框", "type": "boolean" }, 
  "Transfer/filter-placeholder": { "description": "搜索框的占位" }, 
  "Transfer/filter-method": { "description": "自定义搜索函数，入参为 data 和 query，data 为项，query 为当前输入的搜索词" }, 
  "Transfer/not-found-text": { "description": "当列表为空时显示的内容" }, 
  "Transfer/on-change": { "type": "method", "description": "选项在两栏之间转移时的回调函数" }, 
  "Transfer/on-selected-change": { "type": "method", "description": "选中项发生变化时触发" },
  "InputNumber/max": { "description": "最大值" }, 
  "InputNumber/min": { "description": "最小值" }, 
  "InputNumber/value": { "description": "当前值，可以使用 v-model 双向绑定数据" }, 
  "InputNumber/step": { "description": "每次改变的步伐，可以是小数" }, 
  "InputNumber/size": { "description": "输入框尺寸，可选值为large、small、default或者不填", "options": ["large", "small", "default"]}, 
  "InputNumber/disabled": { "description": "设置禁用状态", "type": "boolean" }, 
  "InputNumber/placeholder": { "description": "占位文本" }, 
  "InputNumber/formatter": { "description": "指定输入框展示值的格式" }, 
  "InputNumber/parser": { "description": "指定从 formatter 里转换回数字的方式，和 formatter 搭配使用" }, 
  "InputNumber/readonly": { "description": "是否设置为只读", "type": "boolean" }, 
  "InputNumber/editable": { "description": "是否可编辑", "type": "boolean" }, 
  "InputNumber/precision": { "description": "数值精度" }, 
  "InputNumber/element-id": { "description": "给表单元素设置 id，详见 Form 用法。" }, 
  "InputNumber/on-change": { "type": "method", "description": "数值改变时的回调，返回当前值" }, 
  "InputNumber/on-focus": { "type": "method", "description": "聚焦时触发" }, 
  "InputNumber/on-blur": { "type": "method", "description": "失焦时触发" },
  "Rate/count": { "description": "star 总数" }, 
  "Rate/value": { "description": "当前 star 数，可以使用 v-model 双向绑定数据" }, 
  "Rate/allow-half": { "description": "是否允许半选", "type": "boolean" }, 
  "Rate/disabled": { "description": "是否只读，无法进行交互", "type": "boolean" }, 
  "Rate/show-text": { "description": "是否显示提示文字", "type": "boolean" }, 
  "Rate/clearable": { "description": "是否可以取消选择", "type": "boolean" }, 
  "Rate/on-change": { "type": "method", "description": "评分改变时触发" },
  "Upload/action": { "description": "上传的地址，必填" }, 
  "Upload/headers": { "description": "设置上传的请求头部" }, 
  "Upload/multiple": { "description": "是否支持多选文件", "type": "boolean" }, 
  "Upload/data": { "description": "上传时附带的额外参数" }, 
  "Upload/name": { "description": "上传的文件字段名" }, 
  "Upload/with-credentials": { "description": "支持发送 cookie 凭证信息", "type": "boolean" }, 
  "Upload/show-upload-list": { "description": "是否显示已上传文件列表", "type": "boolean" }, 
  "Upload/type": { "description": "上传控件的类型，可选值为 select（点击选择），drag（支持拖拽）", "options": ["select", "drag"]}, 
  "Upload/accept": { "description": "接受上传的文件类型" }, 
  "Upload/format": { "description": "支持的文件类型，与 accept 不同的是，format 是识别文件的后缀名，accept 为 input 标签原生的 accept 属性，会在选择文件时过滤，可以两者结合使用" }, 
  "Upload/max-size": { "description": "文件大小限制，单位 kb" }, 
  "Upload/before-upload": { "description": "上传文件之前的钩子，参数为上传的文件，若返回 false 或者 Promise 则停止上传" }, 
  "Upload/on-progress": { "description": "文件上传时的钩子，返回字段为 event, file, fileList" }, 
  "Upload/on-success": { "description": "文件上传成功时的钩子，返回字段为 response, file, fileList" }, 
  "Upload/on-error": { "description": "文件上传失败时的钩子，返回字段为 error, file, fileList" }, 
  "Upload/on-preview": { "description": "点击已上传的文件链接时的钩子，返回字段为 file， 可以通过 file.response 拿到服务端返回数据" }, 
  "Upload/on-remove": { "description": "文件列表移除文件时的钩子，返回字段为 file, fileList" }, 
  "Upload/on-format-error": { "description": "文件格式验证失败时的钩子，返回字段为 file, fileList" }, 
  "Upload/on-exceeded-size": { "description": "文件超出指定大小限制时的钩子，返回字段为 file, fileList" }, 
  "Upload/default-file-list": { "description": "默认已上传的文件列表，例如：[{name: 'img1.jpg', url: 'http://www.xxx.com/img1.jpg'}, {name: 'img2.jpg',url: 'http://www.xxx.com/img2.jpg'}]" },
  "Upload/clearFiles": { "type": "method", "description": "清空已上传的文件列表" },
  "ColorPicker/value": { "description": "绑定的值，可使用 v-model 双向绑定" }, 
  "ColorPicker/disabled": { "description": "是否禁用", "type": "boolean" }, 
  "ColorPicker/alpha": { "description": "是否支持透明度选择", "type": "boolean" }, 
  "ColorPicker/hue": { "description": "是否支持色彩选择", "type": "boolean" }, 
  "ColorPicker/recommend": { "description": "是否显示推荐的颜色预设", "type": "boolean" }, 
  "ColorPicker/colors": { "description": "自定义颜色预设" }, 
  "ColorPicker/format": { "description": "颜色的格式，可选值为 hsl、hsv、hex、rgb", "options": ["hsl", "hsv", "hex", "rgb"]}, 
  "ColorPicker/size": { "description": "尺寸，可选值为large、small、default或者不设置", "options": ["large", "small", "default"]}, 
  "ColorPicker/on-change": { "type": "method", "description": "当绑定值变化时触发" }, 
  "ColorPicker/on-active-change": { "type": "method", "description": "面板中当前显示的颜色发生改变时触发" }, 
  "ColorPicker/on-open-change": { "type": "method", "description": "下拉框展开或收起时触发" },
  "Form/model": { "description": "表单数据对象" }, 
  "Form/rules": { "description": "表单验证规则，具体配置查看  async-validator" }, 
  "Form/inline": { "description": "是否开启行内表单模式", "type": "boolean" }, 
  "Form/label-position": { "description": "表单域标签的位置，可选值为 left、right、top", "options": ["left", "right", "top"]}, 
  "Form/label-width": { "description": "表单域标签的宽度，所有的 FormItem 都会继承 Form 组件的 label-width 的值" }, 
  "Form/show-message": { "description": "是否显示校验错误信息", "type": "boolean" }, 
  "Form/autocomplete": { "description": "原生的 autocomplete 属性，可选值为 off 或 on", "options": ["on", "off"]}, 
  "Form/validate": { "type": "method", "description": "对整个表单进行校验，参数为检验完的回调，会返回一个 Boolean 表示成功与失败，支持 Promise" }, 
  "Form/validateField": { "type": "method", "description": "对部分表单字段进行校验的方法，参数1为需校验的 prop，参数2为检验完回调，返回错误信息" }, 
  "Form/resetFields": { "type": "method", "description": "对整个表单进行重置，将所有字段值重置为空并移除校验结果" }, 
  "FormItem/prop": { "description": "对应表单域 model 里的字段" }, 
  "FormItem/label": { "description": "标签文本" }, 
  "FormItem/label-width": { "description": "表单域标签的的宽度" }, 
  "FormItem/label-for": { "description": "指定原生的 label 标签的 for 属性，配合控件的 element-id 属性，可以点击 label 时聚焦控件。" }, 
  "FormItem/required": { "description": "是否必填，如不设置，则会根据校验规则自动生成", "type": "boolean" }, 
  "FormItem/rules": { "description": "表单验证规则" }, 
  "FormItem/error": { "description": "表单域验证错误信息, 设置该值会使表单验证状态变为error，并显示该错误信息" }, 
  "FormItem/show-message": { "description": "是否显示校验错误信息", "type": "boolean" },
  "Alert/type": { "description": "警告提示样式，可选值为info、success、warning、error", "options": ["info", "success", "warning", "error"]}, 
  "Alert/closable": { "description": "是否可关闭", "type": "boolean" }, 
  "Alert/show-icon": { "description": "是否显示图标", "type": "boolean" }, 
  "Alert/on-close": { "type": "method", "description": "关闭时触发" },
  "Card/bordered": { "description": "是否显示边框，建议在灰色背景下使用", "type": "boolean" }, 
  "Card/dis-hover": { "description": "禁用鼠标悬停显示阴影", "type": "boolean" }, 
  "Card/shadow": { "description": "卡片阴影，建议在灰色背景下使用", "type": "boolean" }, 
  "Card/padding": { "description": "卡片内部间距，单位 px" }, 
  "Card/title": { "description": "标题，2.12.0 新增" }, 
  "Card/icon": { "description": "标题前的图标，2.12.0 新增" },
  "Modal/value": { "description": "对话框是否显示，可使用 v-model 双向绑定数据。", "type": "boolean" }, 
  "Modal/title": { "description": "对话框标题，如果使用 slot 自定义了页头，则 title 无效" }, 
  "Modal/closable": { "description": "是否显示右上角的关闭按钮，关闭后 Esc 按键也将关闭", "type": "boolean" }, 
  "Modal/mask-closable": { "description": "是否允许点击遮罩层关闭", "type": "boolean" }, 
  "Modal/loading": { "description": "点击确定按钮时，确定按钮是否显示 loading 状态，开启则需手动设置visible来关闭对话框", "type": "boolean" }, 
  "Modal/scrollable": { "description": "页面是否可以滚动", "type": "boolean" }, 
  "Modal/ok-text": { "description": "确定按钮文字" }, 
  "Modal/cancel-text": { "description": "取消按钮文字" }, 
  "Modal/width": { "description": "对话框宽度，对话框的宽度是响应式的，当屏幕尺寸小于 768px 时，宽度会变为自动auto。当其值不大于 100 时以百分比显示，大于 100 时为像素" }, 
  "Modal/styles": { "description": "设置浮层样式，调整浮层位置等，该属性设置的是.ivu-modal的样式" }, 
  "Modal/class-name": { "description": "设置对话框容器.ivu-modal-wrap的类名，可辅助实现垂直居中等自定义效果" }, 
  "Modal/transition-names": { "description": "自定义显示动画，第一项是模态框，第二项是背景" }, 
  "Modal/transfer": { "description": "是否将弹层放置于 body 内", "type": "boolean" }, 
  "Modal/on-ok": { "type": "method", "description": "点击确定的回调" }, 
  "Modal/on-cancel": { "type": "method", "description": "点击取消的回调" }, 
  "Modal/on-visible-change": { "type": "method", "description": "显示状态发生变化时触发" },
  "Progress/percent": { "description": "百分比" }, 
  "Progress/status": { "description": "状态，可选值为normal、active、wrong、success", "options": ["normal", "active", "wrong", "success"]}, 
  "Progress/stroke-width": { "description": "进度条的线宽，单位 px" }, 
  "Progress/hide-info": { "description": "隐藏数值或状态图标", "type": "boolean" }, 
  "Progress/vertical": { "description": "是否在垂直方向显示", "type": "boolean" },
  "Avatar/shape": { "description": "指定头像的形状，可选值为 circle、square", "options": ["circle", "square"]}, 
  "Avatar/size": { "description": "设置头像的大小，可选值为 large、small、default", "options": ["large", "small", "default"]}, 
  "Avatar/src": { "description": "图片类头像的资源地址" }, 
  "Avatar/icon": { "description": "设置头像的图标类型，参考 Icon 组件" },
  "Badge/count": { "description": "显示的数字，大于overflowCount时，显示${overflowCount}+，为 0 时隐藏" }, 
  "Badge/overflow-count": { "description": "展示封顶的数字值" }, 
  "Badge/dot": { "description": "不展示数字，只有一个小红点，如需隐藏 dot ，需要设置count为 0", "type": "boolean" }, 
  "Badge/class-name": { "description": "自定义的class名称，dot 模式下无效" },
  "Collapse/value": { "description": "当前激活的面板的 name，可以使用 v-model 双向绑定" }, 
  "Collapse/accordion": { "description": "是否开启手风琴模式，开启后每次至多展开一个面板", "type": "boolean" }, 
  "Collapse/on-change": { "type": "method", "description": "切换面板时触发，返回当前已展开的面板的 key，格式为数组" }, 
  "Panel/name": { "description": "当前面板的 name，与 Collapse的value对应，不填为索引值" },
  "Timeline/pending": { "description": "指定是否最后一个节点为幽灵节点", "type": "boolean" }, 
  "TimelineItem/color": { "description": "圆圈颜色，可选值为blue、red、green，或自定义色值", "options": ["blue", "red", "green"]},
  "Tag/closable": { "description": "标签是否可以关闭", "type": "boolean" }, 
  "Tag/checkable": { "description": "标签是否可以选择", "type": "boolean" }, 
  "Tag/checked": { "description": "标签的选中状态", "type": "boolean" }, 
  "Tag/type": { "description": "标签的样式类型，可选值为 border、dot或不填", "options": ["border", "dot"]}, 
  "Tag/color": { "description": "标签颜色，预设颜色值为blue、green、red、yellow、default，你也可以自定义颜色值。" }, 
  "Tag/name": { "description": "当前标签的名称，使用 v-for，并支持关闭时，会比较有用" }, 
  "Tag/fade": { "description": "是否在出现和消失时使用渐变的动画，动画时长可能会引起占位的闪烁", "type": "boolean" }, 
  "Tag/on-close": { "type": "method", "description": "关闭时触发" },
  "Tooltip/content": { "description": "显示的内容" }, 
  "Tooltip/placement": { "description": "提示框出现的位置，2.12.0 版本开始支持自动识别", "options": ["top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end", "left", "left-start", "left-end", "right", "right-start", "right-end"]}, 
  "Tooltip/disabled": { "description": "是否禁用提示框", "type": "boolean" }, 
  "Tooltip/delay": { "description": "延迟显示，单位毫秒" }, 
  "Tooltip/always": { "description": "是否总是可见", "type": "boolean" }, 
  "Tooltip/transfer": { "description": "是否将弹层放置于 body 内，在 Tabs、带有 fixed 的 Table 列内使用时，建议添加此属性，它将不受父级样式影响，从而达到更好的效果", "type": "boolean" }, 
  "Tooltip/options": { "description": "自定义 popper.js 的配置项，具体配置见 popper.js 文档" }, 
  "Tooltip/on-popper-show": { "type": "method", "description": "在提示框显示时触发" }, 
  "Tooltip/on-popper-hide": { "type": "method", "description": "在提示框消失时触发" },
  "Poptip/trigger": { "description": "触发方式，可选值为hover（悬停）click（点击）focus（聚焦）,在 confirm 模式下，只有 click 有效", "options": ["hover", "click", "focus"]}, 
  "Poptip/title": { "description": "显示的标题" }, 
  "Poptip/content": { "description": "显示的正文内容，只在非 confirm 模式下有效" }, 
  "Poptip/placement": { "description": "提示框出现的位置，2.12.0 版本开始支持自动识别", "options": ["top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end", "left", "left-start", "left-end", "right", "right-start", "right-end"]}, 
  "Poptip/width": { "description": "宽度，最小宽度为 150px，在 confirm 模式下，默认最大宽度为 300px" }, 
  "Poptip/confirm": { "description": "是否开启对话框模式", "type": "boolean" }, 
  "Poptip/ok-text": { "description": "确定按钮的文字，只在 confirm 模式下有效" }, 
  "Poptip/cancel-text": { "description": "取消按钮的文字，只在 confirm 模式下有效" }, 
  "Poptip/transfer": { "description": "是否将弹层放置于 body 内，在 Tabs、带有 fixed 的 Table 列内使用时，建议添加此属性，它将不受父级样式影响，从而达到更好的效果", "type": "boolean" }, 
  "Poptip/popper-class": { "description": "给 Poptip 设置 class-name，在使用 transfer 时会很有用" }, 
  "Poptip/options": { "description": "自定义 popper.js 的配置项，具体配置见 popper.js 文档" }, 
  "Poptip/on-popper-show": { "type": "method", "description": "在提示框显示时触发" }, 
  "Poptip/on-popper-hide": { "type": "method", "description": "在提示框消失时触发" }, 
  "Poptip/on-ok": { "type": "method", "description": "点击确定的回调，只在 confirm 模式下有效" }, 
  "Poptip/on-cancel": { "type": "method", "description": "点击取消的回调，只在 confirm 模式下有效" },
  "Carousel/value": { "description": "幻灯片的索引，从 0 开始，可以使用 v-model 双向绑定数据" }, 
  "Carousel/height": { "description": "走马灯的高度，可填 auto 或具体高度数值，单位 px" }, 
  "Carousel/loop": { "description": "是否开启循环", "type": "boolean" }, 
  "Carousel/autoplay": { "description": "是否自动切换", "type": "boolean" }, 
  "Carousel/autoplay-speed": { "description": "自动切换的时间间隔，单位为毫秒" }, 
  "Carousel/dots": { "description": "指示器的位置，可选值为 inside （内部），outside（外部），none（不显示）", "options": ["inside", "outside", "none"]}, 
  "Carousel/radius-dot": { "description": "是否显示圆形指示器", "type": "boolean" }, 
  "Carousel/trigger": { "description": "指示器的触发方式，可选值为 click（点击），hover（悬停）", "options": ["click", "hover"]}, 
  "Carousel/arrow": { "description": "切换箭头的显示时机，可选值为 hover（悬停），always（一直显示），never（不显示）", "options": ["hover", "always", "never"]}, 
  "Carousel/easing": { "description": "动画效果" }, 
  "Carousel/on-change": { "type": "method", "description": "幻灯片切换时触发，目前激活的幻灯片的索引，原幻灯片的索引" },
  "Tree/data": { "description": "可嵌套的节点属性的数组，生成 tree 的数据" }, 
  "Tree/multiple": { "description": "是否支持多选", "type": "boolean" }, 
  "Tree/show-checkbox": { "description": "是否显示多选框", "type": "boolean" }, 
  "Tree/empty-text": { "description": "没有数据时的提示" }, 
  "Tree/load-data": { "description": "异步加载数据的方法，见示例" }, 
  "Tree/render": { "description": "自定义渲染内容，见示例" }, 
  "Tree/children-key": { "description": "定义子节点键" }, 
  "Tree/on-select-change": { "type": "method", "description": "点击树节点时触发" }, 
  "Tree/on-check-change": { "type": "method", "description": "点击复选框时触发" }, 
  "Tree/on-toggle-expand": { "type": "method", "description": "展开和收起子列表时触发" }, 
  "Tree/getCheckedNodes": { "type": "method", "description": "获取被勾选的节点" }, 
  "Tree/getSelectedNodes": { "type": "method", "description": "获取被选中的节点" },
  "Menu/mode": { "description": "菜单类型，可选值为 horizontal（水平） 和 vertical（垂直）", "options": ["horizontal", "vertical"]}, 
  "Menu/theme": { "description": "主题，可选值为 light、dark、primary，其中 primary 只适用于 mode=horizontal", "options": ["light", "dark", "primary"]}, 
  "Menu/active-name": { "description": "激活菜单的 name 值" }, 
  "Menu/open-names": { "description": "展开的 Submenu 的 name 集合" }, 
  "Menu/accordion": { "description": "是否开启手风琴模式，开启后每次至多展开一个子菜单", "type": "boolean" }, 
  "Menu/width": { "description": "导航菜单的宽度，只在 mode=vertical时有效，如果使用 Col 等布局，建议设置为 auto" }, 
  "Menu/on-select": { "type": "method", "description": "选择菜单（MenuItem）时触发" }, 
  "Menu/on-open-change": { "type": "method", "description": "当 展开/收起 子菜单时触发" }, 
  "Menu/updateOpened": { "type": "method", "description": "手动更新展开的子目录，注意要在 $nextTick 里调用" }, 
  "Menu/updateActiveName": { "type": "method", "description": "手动更新当前选择项，注意要在 $nextTick 里调用" }, 
  "MenuItem/name": { "description": "菜单项的唯一标识，必填" }, 
  "Submenu/name": { "description": "子菜单的唯一标识，必填" }, 
  "MenuGroup/title": { "description": "分组标题" },
  "Tabs/value": { "description": "当前激活 tab 面板的 name，可以使用 v-model 双向绑定数据" }, 
  "Tabs/type": { "description": "页签的基本样式，可选值为 line 和 card", "options": ["line", "card"]}, 
  "Tabs/size": { "description": "尺寸，可选值为 default 和 small，仅在 type=line 时有效", "options": ["default", "small"]}, 
  "Tabs/closable": { "description": "是否可以关闭页签，仅在 type=card 时有效", "type": "boolean" }, 
  "Tabs/animated": { "description": "是否使用 CSS3 动画", "type": "boolean" }, 
  "Tabs/capture-focus": { "description": "Tabs 内的表单类组件是否自动获得焦点", "type": "boolean" }, 
  "Tabs/on-click": { "type": "method", "description": "tab 被点击时触发" }, 
  "Tabs/on-tab-remove": { "type": "method", "description": "tab 被关闭时触发" }, 
  "TabPane/name": { "description": "用于标识当前面板，对应 value，默认为其索引值" }, 
  "TabPane/label": { "description": "选项卡头显示文字，支持 Render 函数。  学习 Render 函数的内容" }, 
  "TabPane/icon": { "description": "选项卡图标" }, 
  "TabPane/disabled": { "description": "是否禁用该选项卡", "type": "boolean" }, 
  "TabPane/closable": { "description": "是否可以关闭页签，仅在 type=card 时有效", "type": "boolean" },
  "Dropdown/trigger": { "description": "触发方式，可选值为 hover（悬停）click（点击）custom（自定义），使用 custom 时，需配合 visible 一起使用", "options": ["hover", "click", "custom"]}, 
  "Dropdown/visible": { "description": "手动控制下拉框的显示，在 trigger = 'custom' 时使用", "type": "boolean" }, 
  "Dropdown/placement": { "description": "下拉菜单出现的位置，2.12.0 版本开始支持自动识别", "options": ["top", "top-start", "top-end", "bottom", "bottom-start", "bottom-end", "left", "left-start", "left-end", "right", "right-start", "right-end"]}, 
  "Dropdown/transfer": { "description": "是否将弹层放置于 body 内，在 Tabs、带有 fixed 的 Table 列内使用时，建议添加此属性，它将不受父级样式影响，从而达到更好的效果", "type": "boolean" }, 
  "Dropdown/on-click": { "type": "method", "description": "点击菜单项时触发" }, 
  "Dropdown/on-visible-change": { "type": "method", "description": "菜单显示状态改变时调用" }, 
  "Dropdown/on-clickoutside": { "type": "method", "description": "点击外部关闭下拉菜单时触发" }, 
  "DropdownItem/name": { "description": "用来标识这一项" }, 
  "DropdownItem/disabled": { "description": "禁用该项", "type": "boolean" }, 
  "DropdownItem/divided": { "description": "显示分割线", "type": "boolean" }, 
  "DropdownItem/selected": { "description": "标记该项为选中状态", "type": "boolean" },
  "Page/current": { "description": "当前页码，支持 .sync 修饰符" }, 
  "Page/total": { "description": "数据总数" }, 
  "Page/page-size": { "description": "每页条数" }, 
  "Page/page-size-opts": { "description": "每页条数切换的配置" }, 
  "Page/placement": { "description": "条数切换弹窗的展开方向，可选值为 bottom 和 top", "options": ["top", "bottom"]}, 
  "Page/size": { "description": "可选值为small（迷你版）或不填（默认）", "options": ["small"]}, 
  "Page/simple": { "description": "简洁版", "type": "boolean" }, 
  "Page/show-total": { "description": "显示总数", "type": "boolean" }, 
  "Page/show-elevator": { "description": "显示电梯，可以快速切换到某一页", "type": "boolean" }, 
  "Page/show-sizer": { "description": "显示分页，用来改变page-size", "type": "boolean" }, 
  "Page/class-name": { "description": "自定义 class 名称" }, 
  "Page/styles": { "description": "自定义 style 样式" }, 
  "Page/transfer": { "description": "是否将弹层放置于 body 内，在 Tabs、带有 fixed 的 Table 列内使用时，建议添加此属性，它将不受父级样式影响，从而达到更好的效果", "type": "boolean" }, 
  "Page/on-change": { "type": "method", "description": "页码改变的回调，返回改变后的页码" }, 
  "Page/on-page-size-change": { "type": "method", "description": "切换每页条数时的回调，返回切换后的每页条数" },
  "Breadcrumb/separator": { "description": "自定义分隔符" }, 
  "BreadcrumbItem/to": { "description": "链接，不传则没有链接" }, 
  "BreadcrumbItem/href": { "description": "同 to，未来将废弃" }, 
  "BreadcrumbItem/replace": { "description": "路由跳转时，开启 replace 将不会向 history 添加新记录", "type": "boolean" },
  "Steps/current": { "description": "当前步骤，从 0 开始计数" }, 
  "Steps/status": { "description": "当前步骤的状态，可选值为wait、process、finish、error", "options": ["wait", "process", "finish", "error"]}, 
  "Steps/size": { "description": "步骤条的尺寸，可选值为small或者不写", "options": ["small"]}, 
  "Steps/direction": { "description": "步骤条的方向，可选值为horizontal（水平）或vertical（垂直）", "options": ["horizontal", "vertical"]}, 
  "Step/status": { "description": "步骤的状态，可选值为wait、process、finish、error，不设置时自动判断", "options": ["wait", "process", "finish", "error"]}, 
  "Step/title": { "description": "标题" }, 
  "Step/content": { "description": "步骤的详细描述，可选" }, 
  "Step/icon": { "description": "步骤的图标，可选" },
  "Circle/percent": { "description": "百分比" }, 
  "Circle/size": { "description": "图表的宽度和高度，单位 px" }, 
  "Circle/stroke-linecap": { "description": "进度环顶端的形状，可选值为square（方）和round（圆）", "options": ["square", "round"]}, 
  "Circle/stroke-width": { "description": "进度环的线宽，单位 px" }, 
  "Circle/stroke-color": { "description": "进度环的颜色" }, 
  "Circle/trail-width": { "description": "进度环背景的线宽，单位 px" }, 
  "Circle/trail-color": { "description": "进度环背景的颜色" },
  "Affix/offset-top": { "description": "距离窗口顶部达到指定偏移量后触发" }, 
  "Affix/offset-bottom": { "description": "距离窗口底部达到指定偏移量后触发" }, 
  "Affix/on-change": { "type": "method", "description": "在固定状态发生改变时触发" },
  "BackTop/height": { "description": "页面滚动高度达到该值时才显示BackTop组件" }, 
  "BackTop/bottom": { "description": "组件距离底部的距离" }, 
  "BackTop/right": { "description": "组件距离右部的距离" }, 
  "BackTop/duration": { "description": "滚动动画持续时间，单位 毫秒" }, 
  "BackTop/on-click": { "type": "method", "description": "点击按钮时触发" },
  "Spin/size": { "description": "Spin尺寸，可选值为large和small或者不设置", "options": ["large", "small"]}, 
  "Spin/fix": { "description": "是否固定，需要父级有relative或absolute", "type": "boolean" },
  "Scroll/height": { "description": "滚动区域的高度，单位像素" }, 
  "Scroll/loading-text": { "description": "加载中的文案" }, 
  "Scroll/on-reach-top": { "description": "滚动至顶部时触发，需返回 Promise" }, 
  "Scroll/on-reach-bottom": { "description": "滚动至底部时触发，需返回 Promise" }, 
  "Scroll/on-reach-edge": { "description": "滚动至顶部或底部时触发，需返回 Promise" }, 
  "Scroll/distance-to-edge": { "description": "从边缘到触发回调的距离。如果是负的，回调将在到达边缘之前触发。值最好在 24 以下。" }
}