export default {
    "el-button:type": "<el-button type=\"$1\">$2</el-button>",
    "el-button": "<el-button>$1</el-button>",
    "el-button:icon": "<el-button :icon=\"$1\">$2</el-button>",
    "el-button:key": "<el-button :key=\"$1\">$2</el-button>",
    "el-icon": "<el-icon>$1</el-icon>",
    "el-button-group": "<el-button-group>$1</el-button-group>",
    "el-button:size": "<el-button size=\"$1\">$2</el-button>",
    "el-button:tag": "<el-button tag=\"$1\">$2</el-button>",
    "el-button:dark": "<el-button :dark=\"$1\">$2</el-button>",
    "el-row:gutter": "<el-row :gutter=\"$1\">$2</el-row>",
    "el-col:key": "<el-col :key=\"$1\">$2</el-col>",
    "el-aside:width": "<el-aside width=\"$1\">$2</el-aside>",
    "el-container": "<el-container>$1</el-container>",
    "el-menu": "<el-menu>$1</el-menu>",
    "el-sub-menu:index": "<el-sub-menu index=\"$1\">$2</el-sub-menu>",
    "el-menu-item": "<el-menu-item>$1</el-menu-item>",
    "el-menu-item-group": "<el-menu-item-group>$1</el-menu-item-group>",
    "el-sub-menu": "<el-sub-menu>$1</el-sub-menu>",
    "el-header": "<el-header>$1</el-header>",
    "el-table:data": "<el-table :data=\"$1\">$2</el-table>",
    "el-table-column:prop": "<el-table-column prop=\"$1\">$2</el-table-column>",
    "el-icon:size": "<el-icon :size=\"$1\">$2</el-icon>",
    "el-col:span": "<el-col :span=\"$1\">$2</el-col>",
    "el-row": "<el-row>$1</el-row>",
    "el-row:justify": "<el-row justify=\"$1\">$2</el-row>",
    "el-col:xs": "<el-col :xs=\"$1\">$2</el-col>",
    "el-link:target": "<el-link target=\"$1\">$2</el-link>",
    "el-link:type": "<el-link type=\"$1\">$2</el-link>",
    "el-link": "<el-link>$1</el-link>",
    "el-link:underline": "<el-link :underline=\"$1\">$2</el-link>",
    "el-link:icon": "<el-link :icon=\"$1\">$2</el-link>",
    "el-text": "<el-text>$1</el-text>",
    "el-text:type": "<el-text type=\"$1\">$2</el-text>",
    "el-text:size": "<el-text size=\"$1\">$2</el-text>",
    "el-text:line-clamp": "<el-text line-clamp=\"$1\">$2</el-text>",
    "el-space:direction": "<el-space direction=\"$1\">$2</el-space>",
    "el-text:tag": "<el-text tag=\"$1\">$2</el-text>",
    "el-rate": "<el-rate>$1</el-rate>",
    "el-scrollbar:height": "<el-scrollbar height=\"$1\">$2</el-scrollbar>",
    "el-scrollbar:max-height": "<el-scrollbar max-height=\"$1\">$2</el-scrollbar>",
    "el-scrollbar:ref": "<el-scrollbar ref=\"$1\">$2</el-scrollbar>",
    "el-slider:v-model": "<el-slider v-model=\"$1\">$2</el-slider>",
    "el-space": "<el-space>$1</el-space>",
    "el-card:key": "<el-card :key=\"$1\">$2</el-card>",
    "el-button:class": "<el-button class=\"$1\">$2</el-button>",
    "el-radio-group:v-model": "<el-radio-group v-model=\"$1\">$2</el-radio-group>",
    "el-radio:value": "<el-radio value=\"$1\">$2</el-radio>",
    "el-space:size": "<el-space :size=\"$1\">$2</el-space>",
    "el-switch:v-model": "<el-switch v-model=\"$1\">$2</el-switch>",
    "el-space:fill": "<el-space :fill=\"$1\">$2</el-space>",
    "el-radio:v-model": "<el-radio v-model=\"$1\">$2</el-radio>",
    "el-space:fill-ratio": "<el-space :fill-ratio=\"$1\">$2</el-space>",
    "el-config-provider:locale": "<el-config-provider :locale=\"$1\">$2</el-config-provider>",
    "el-table": "<el-table>$1</el-table>",
    "el-pagination:total": "<el-pagination :total=\"$1\">$2</el-pagination>",
    "el-checkbox:v-model": "<el-checkbox v-model=\"$1\">$2</el-checkbox>",
    "el-config-provider:button": "<el-config-provider :button=\"$1\">$2</el-config-provider>",
    "el-config-provider:message": "<el-config-provider :message=\"$1\">$2</el-config-provider>",
    "el-autocomplete:v-model": "<el-autocomplete v-model=\"$1\">$2</el-autocomplete>",
    "el-cascader:v-model": "<el-cascader v-model=\"$1\">$2</el-cascader>",
    "el-cascader:options": "<el-cascader :options=\"$1\">$2</el-cascader>",
    "el-cascader:props": "<el-cascader :props=\"$1\">$2</el-cascader>",
    "el-cascader-panel:options": "<el-cascader-panel :options=\"$1\">$2</el-cascader-panel>",
    "el-checkbox-group:v-model": "<el-checkbox-group v-model=\"$1\">$2</el-checkbox-group>",
    "el-checkbox": "<el-checkbox>$1</el-checkbox>",
    "el-checkbox:label": "<el-checkbox label=\"$1\">$2</el-checkbox>",
    "el-checkbox:key": "<el-checkbox :key=\"$1\">$2</el-checkbox>",
    "el-checkbox-button:key": "<el-checkbox-button :key=\"$1\">$2</el-checkbox-button>",
    "el-color-picker:v-model": "<el-color-picker v-model=\"$1\">$2</el-color-picker>",
    "el-radio-button:value": "<el-radio-button value=\"$1\">$2</el-radio-button>",
    "el-date-picker:v-model": "<el-date-picker v-model=\"$1\">$2</el-date-picker>",
    "el-form:model": "<el-form :model=\"$1\">$2</el-form>",
    "el-form-item": "<el-form-item>$1</el-form-item>",
    "el-input:v-model": "<el-input v-model=\"$1\">$2</el-input>",
    "el-select:v-model": "<el-select v-model=\"$1\">$2</el-select>",
    "el-option:value": "<el-option value=\"$1\">$2</el-option>",
    "el-time-picker:v-model": "<el-time-picker v-model=\"$1\">$2</el-time-picker>",
    "el-checkbox:name": "<el-checkbox name=\"$1\">$2</el-checkbox>",
    "el-form-item:label": "<el-form-item label=\"$1\">$2</el-form-item>",
    "el-form:inline": "<el-form :inline=\"$1\">$2</el-form>",
    "el-form:label-position": "<el-form :label-position=\"$1\">$2</el-form>",
    "el-form:ref": "<el-form ref=\"$1\">$2</el-form>",
    "el-form-item:prop": "<el-form-item prop=\"$1\">$2</el-form-item>",
    "el-input": "<el-input>$1</el-input>",
    "el-form-item:key": "<el-form-item :key=\"$1\">$2</el-form-item>",
    "el-input:type": "<el-input type=\"$1\">$2</el-input>",
    "el-checkbox-button:name": "<el-checkbox-button name=\"$1\">$2</el-checkbox-button>",
    "el-alert:type": "<el-alert type=\"$1\">$2</el-alert>",
    "el-option:label": "<el-option label=\"$1\">$2</el-option>",
    "el-input-number:v-model": "<el-input-number v-model=\"$1\">$2</el-input-number>",
    "el-radio-button": "<el-radio-button>$1</el-radio-button>",
    "el-radio-button:label": "<el-radio-button label=\"$1\">$2</el-radio-button>",
    "el-rate:v-model": "<el-rate v-model=\"$1\">$2</el-rate>",
    "el-option:key": "<el-option :key=\"$1\">$2</el-option>",
    "el-option-group:key": "<el-option-group :key=\"$1\">$2</el-option-group>",
    "el-tag:color": "<el-tag :color=\"$1\">$2</el-tag>",
    "el-tag:key": "<el-tag :key=\"$1\">$2</el-tag>",
    "el-tooltip:placement": "<el-tooltip placement=\"$1\">$2</el-tooltip>",
    "el-transfer:v-model": "<el-transfer v-model=\"$1\">$2</el-transfer>",
    "el-upload:v-model:file-list": "<el-upload v-model:file-list=\"$1\">$2</el-upload>",
    "el-upload:ref": "<el-upload ref=\"$1\">$2</el-upload>",
    "el-upload:show-file-list": "<el-upload :show-file-list=\"$1\">$2</el-upload>",
    "el-dialog:v-model": "<el-dialog v-model=\"$1\">$2</el-dialog>",
    "el-upload:auto-upload": "<el-upload :auto-upload=\"$1\">$2</el-upload>",
    "el-upload": "<el-upload>$1</el-upload>",
    "el-avatar:size": "<el-avatar :size=\"$1\">$2</el-avatar>",
    "el-avatar:shape": "<el-avatar shape=\"$1\">$2</el-avatar>",
    "el-avatar:icon": "<el-avatar :icon=\"$1\">$2</el-avatar>",
    "el-avatar": "<el-avatar>$1</el-avatar>",
    "el-calendar:v-model": "<el-calendar v-model=\"$1\">$2</el-calendar>",
    "el-calendar": "<el-calendar>$1</el-calendar>",
    "el-calendar:ref": "<el-calendar ref=\"$1\">$2</el-calendar>",
    "el-card": "<el-card>$1</el-card>",
    "el-card:shadow": "<el-card shadow=\"$1\">$2</el-card>",
    "el-carousel:height": "<el-carousel height=\"$1\">$2</el-carousel>",
    "el-carousel-item:key": "<el-carousel-item :key=\"$1\">$2</el-carousel-item>",
    "el-carousel:trigger": "<el-carousel trigger=\"$1\">$2</el-carousel>",
    "el-carousel:indicator-position": "<el-carousel indicator-position=\"$1\">$2</el-carousel>",
    "el-carousel:interval": "<el-carousel :interval=\"$1\">$2</el-carousel>",
    "el-carousel-item": "<el-carousel-item>$1</el-carousel-item>",
    "el-collapse:v-model": "<el-collapse v-model=\"$1\">$2</el-collapse>",
    "el-collapse-item:title": "<el-collapse-item title=\"$1\">$2</el-collapse-item>",
    "el-collapse": "<el-collapse>$1</el-collapse>",
    "el-collapse-item:name": "<el-collapse-item name=\"$1\">$2</el-collapse-item>",
    "el-descriptions": "<el-descriptions>$1</el-descriptions>",
    "el-descriptions-item:label": "<el-descriptions-item label=\"$1\">$2</el-descriptions-item>",
    "el-tag:size": "<el-tag size=\"$1\">$2</el-tag>",
    "el-descriptions:column": "<el-descriptions :column=\"$1\">$2</el-descriptions>",
    "el-icon:style": "<el-icon :style=\"$1\">$2</el-icon>",
    "el-descriptions:direction": "<el-descriptions direction=\"$1\">$2</el-descriptions>",
    "el-empty:description": "<el-empty description=\"$1\">$2</el-empty>",
    "el-empty": "<el-empty>$1</el-empty>",
    "el-empty:image-size": "<el-empty :image-size=\"$1\">$2</el-empty>",
    "el-image:src": "<el-image :src=\"$1\">$2</el-image>",
    "el-image": "<el-image>$1</el-image>",
    "el-image:key": "<el-image :key=\"$1\">$2</el-image>",
    "el-pagination:page-size": "<el-pagination :page-size=\"$1\">$2</el-pagination>",
    "el-pagination:hide-on-single-page": "<el-pagination :hide-on-single-page=\"$1\">$2</el-pagination>",
    "el-pagination:v-model:current-page": "<el-pagination v-model:current-page=\"$1\">$2</el-pagination>",
    "el-progress:percentage": "<el-progress :percentage=\"$1\">$2</el-progress>",
    "el-progress:text-inside": "<el-progress :text-inside=\"$1\">$2</el-progress>",
    "el-progress:type": "<el-progress type=\"$1\">$2</el-progress>",
    "el-col:sm": "<el-col :sm=\"$1\">$2</el-col>",
    "el-result:icon": "<el-result icon=\"$1\">$2</el-result>",
    "el-result:title": "<el-result title=\"$1\">$2</el-result>",
    "el-skeleton": "<el-skeleton>$1</el-skeleton>",
    "el-skeleton-item:variant": "<el-skeleton-item variant=\"$1\">$2</el-skeleton-item>",
    "el-skeleton:rows": "<el-skeleton :rows=\"$1\">$2</el-skeleton>",
    "el-skeleton:loading": "<el-skeleton :loading=\"$1\">$2</el-skeleton>",
    "el-table-column:fixed": "<el-table-column fixed=\"$1\">$2</el-table-column>",
    "el-table-column": "<el-table-column>$1</el-table-column>",
    "el-table:ref": "<el-table ref=\"$1\">$2</el-table>",
    "el-table-column:type": "<el-table-column type=\"$1\">$2</el-table-column>",
    "el-table-column:property": "<el-table-column property=\"$1\">$2</el-table-column>",
    "el-table-column:label": "<el-table-column label=\"$1\">$2</el-table-column>",
    "el-tag": "<el-tag>$1</el-tag>",
    "el-popover:effect": "<el-popover effect=\"$1\">$2</el-popover>",
    "el-table-column:align": "<el-table-column align=\"$1\">$2</el-table-column>",
    "el-image:preview-src-list": "<el-image :preview-src-list=\"$1\">$2</el-image>",
    "el-tag:type": "<el-tag type=\"$1\">$2</el-tag>",
    "el-check-tag": "<el-check-tag>$1</el-check-tag>",
    "el-check-tag:checked": "<el-check-tag :checked=\"$1\">$2</el-check-tag>",
    "el-timeline": "<el-timeline>$1</el-timeline>",
    "el-timeline-item:key": "<el-timeline-item :key=\"$1\">$2</el-timeline-item>",
    "el-timeline-item:placement": "<el-timeline-item placement=\"$1\">$2</el-timeline-item>",
    "el-divider": "<el-divider>$1</el-divider>",
    "el-button:ref": "<el-button ref=\"$1\">$2</el-button>",
    "el-tour:v-model": "<el-tour v-model=\"$1\">$2</el-tour>",
    "el-tour-step": "<el-tour-step>$1</el-tour-step>",
    "el-tour-step:title": "<el-tour-step title=\"$1\">$2</el-tour-step>",
    "el-tour-step:mask": "<el-tour-step :mask=\"$1\">$2</el-tour-step>",
    "el-button:id": "<el-button id=\"$1\">$2</el-button>",
    "el-tour-step:target": "<el-tour-step :target=\"$1\">$2</el-tour-step>",
    "el-tree:data": "<el-tree :data=\"$1\">$2</el-tree>",
    "el-tree:props": "<el-tree :props=\"$1\">$2</el-tree>",
    "el-tree:ref": "<el-tree ref=\"$1\">$2</el-tree>",
    "el-tree:allow-drop": "<el-tree :allow-drop=\"$1\">$2</el-tree>",
    "el-tree-select:v-model": "<el-tree-select v-model=\"$1\">$2</el-tree-select>",
    "el-statistic:value": "<el-statistic :value=\"$1\">$2</el-statistic>",
    "el-countdown:value": "<el-countdown :value=\"$1\">$2</el-countdown>",
    "el-tooltip:effect": "<el-tooltip effect=\"$1\">$2</el-tooltip>",
    "el-affix:offset": "<el-affix :offset=\"$1\">$2</el-affix>",
    "el-affix:position": "<el-affix position=\"$1\">$2</el-affix>",
    "el-anchor:offset": "<el-anchor :offset=\"$1\">$2</el-anchor>",
    "el-anchor-link": "<el-anchor-link>$1</el-anchor-link>",
    "el-anchor:container": "<el-anchor :container=\"$1\">$2</el-anchor>",
    "el-anchor-link:title": "<el-anchor-link title=\"$1\">$2</el-anchor-link>",
    "el-anchor:type": "<el-anchor type=\"$1\">$2</el-anchor>",
    "el-breadcrumb": "<el-breadcrumb>$1</el-breadcrumb>",
    "el-breadcrumb-item": "<el-breadcrumb-item>$1</el-breadcrumb-item>",
    "el-breadcrumb:separator-icon": "<el-breadcrumb :separator-icon=\"$1\">$2</el-breadcrumb>",
    "el-dropdown-item": "<el-dropdown-item>$1</el-dropdown-item>",
    "el-dropdown:type": "<el-dropdown type=\"$1\">$2</el-dropdown>",
    "el-dropdown-item:icon": "<el-dropdown-item :icon=\"$1\">$2</el-dropdown-item>",
    "el-dropdown:trigger": "<el-dropdown trigger=\"$1\">$2</el-dropdown>",
    "el-dropdown:hide-on-click": "<el-dropdown :hide-on-click=\"$1\">$2</el-dropdown>",
    "el-dropdown": "<el-dropdown>$1</el-dropdown>",
    "el-dropdown-item:command": "<el-dropdown-item command=\"$1\">$2</el-dropdown-item>",
    "el-dropdown:ref": "<el-dropdown ref=\"$1\">$2</el-dropdown>",
    "el-dropdown:size": "<el-dropdown size=\"$1\">$2</el-dropdown>",
    "el-menu:default-active": "<el-menu :default-active=\"$1\">$2</el-menu>",
    "el-menu-item:index": "<el-menu-item index=\"$1\">$2</el-menu-item>",
    "el-row:class": "<el-row class=\"$1\">$2</el-row>",
    "el-menu:mode": "<el-menu mode=\"$1\">$2</el-menu>",
    "el-sub-menu:popper-offset": "<el-sub-menu :popper-offset=\"$1\">$2</el-sub-menu>",
    "el-page-header": "<el-page-header>$1</el-page-header>",
    "el-page-header:icon": "<el-page-header :icon=\"$1\">$2</el-page-header>",
    "el-steps:active": "<el-steps :active=\"$1\">$2</el-steps>",
    "el-step": "<el-step>$1</el-step>",
    "el-steps:space": "<el-steps :space=\"$1\">$2</el-steps>",
    "el-step:title": "<el-step title=\"$1\">$2</el-step>",
    "el-step:icon": "<el-step :icon=\"$1\">$2</el-step>",
    "el-steps:direction": "<el-steps direction=\"$1\">$2</el-steps>",
    "el-tabs:v-model": "<el-tabs v-model=\"$1\">$2</el-tabs>",
    "el-tab-pane:label": "<el-tab-pane label=\"$1\">$2</el-tab-pane>",
    "el-tabs": "<el-tabs>$1</el-tabs>",
    "el-tabs:tab-position": "<el-tabs :tab-position=\"$1\">$2</el-tabs>",
    "el-tab-pane:key": "<el-tab-pane :key=\"$1\">$2</el-tab-pane>",
    "el-form-item:label-width": "<el-form-item :label-width=\"$1\">$2</el-form-item>",
    "el-drawer:v-model": "<el-drawer v-model=\"$1\">$2</el-drawer>",
    "el-drawer:ref": "<el-drawer ref=\"$1\">$2</el-drawer>",
    "el-table:v-loading": "<el-table v-loading=\"$1\">$2</el-table>",
    "el-button:plain": "<el-button :plain=\"$1\">$2</el-button>",
    "el-popconfirm": "<el-popconfirm>$1</el-popconfirm>",
    "el-popconfirm:width": "<el-popconfirm width=\"$1\">$2</el-popconfirm>",
    "el-popconfirm:confirm-button-text": "<el-popconfirm confirm-button-text=\"$1\">$2</el-popconfirm>",
    "el-popover:title": "<el-popover title=\"$1\">$2</el-popover>",
    "el-popover:placement": "<el-popover placement=\"$1\">$2</el-popover>",
    "el-popover:ref": "<el-popover ref=\"$1\">$2</el-popover>",
    "el-popover:visible": "<el-popover :visible=\"$1\">$2</el-popover>",
    "el-table-column:width": "<el-table-column width=\"$1\">$2</el-table-column>",
    "el-popover:width": "<el-popover :width=\"$1\">$2</el-popover>",
    "el-button:v-popover": "<el-button v-popover=\"$1\">$2</el-button>",
    "el-tooltip:disabled": "<el-tooltip :disabled=\"$1\">$2</el-tooltip>",
    "el-tooltip": "<el-tooltip>$1</el-tooltip>",
    "el-tooltip:v-model:visible": "<el-tooltip v-model:visible=\"$1\">$2</el-tooltip>",
    "el-tooltip:ref": "<el-tooltip ref=\"$1\">$2</el-tooltip>",
    "el-tooltip:visible": "<el-tooltip :visible=\"$1\">$2</el-tooltip>",
    "el-divider:content-position": "<el-divider content-position=\"$1\">$2</el-divider>",
    "el-divider:border-style": "<el-divider border-style=\"$1\">$2</el-divider>",
    "el-divider:direction": "<el-divider direction=\"$1\">$2</el-divider>",
    "el-watermark:font": "<el-watermark :font=\"$1\">$2</el-watermark>",
    "el-watermark:width": "<el-watermark :width=\"$1\">$2</el-watermark>",
    "el-watermark:class": "<el-watermark class=\"$1\">$2</el-watermark>",
    "el-form:class": "<el-form class=\"$1\">$2</el-form>",
    "el-input-number:controls-position": "<el-input-number controls-position=\"$1\">$2</el-input-number>",
    "el-input-number:placeholder": "<el-input-number placeholder=\"$1\">$2</el-input-number>"
}