export default {
  "van-button/type": {"options": ["primary", "info", "warning", "danger"]},
  "van-button/size": {"options": ["normal", "large", "small", "mini"]},
  "van-button/plain": {"type": "boolean"},
  "van-button/block": {"type": "boolean"},
  "van-button/round": {"type": "boolean"},
  "van-button/square": {"type": "boolean"},
  "van-button/disabled": {"type": "boolean"},
  "van-button/hairline": {"type": "boolean"},
  "van-button/loading": {"type": "boolean"},
  "van-button/dataset": {"options": ["share", "event.target.dataset.detail"]},
  "van-button/form-type": {"options": ["submit", "reset"]},
  "van-cell/border": {"type": "boolean"},
  "van-cell/center": {"type": "boolean"},
  "van-cell/link-type": {"options": ["redirectTo", "switchTab", "reLaunch"]},
  "van-cell/clickable": {"type": "boolean"},
  "van-cell/is-link": {"type": "boolean"},
  "van-cell/required": {"type": "boolean"},
  "van-cell/arrow-direction": {"options": ["left", "up", "down"]},
  "van-cell/use-label-slot": {"type": "boolean"},
  "van-cell-group/inset": {"type": "boolean"},
  "van-cell-group/border": {"type": "boolean"},
  "van-icon/dot": {"type": "boolean"},
  "van-icon/size": {"options": ["20px", "2em", "px"]},
  "van-image/round": {"type": "boolean"},
  "van-image/lazy-load": {"type": "boolean"},
  "van-image/show-error": {"type": "boolean"},
  "van-image/show-loading": {"type": "boolean"},
  "van-image/use-error-slot": {"type": "boolean"},
  "van-image/use-loading-slot": {"type": "boolean"},
  "van-image/show-menu-by-longpress": {"type": "boolean"},
  "van-popup/show": {"type": "boolean"},
  "van-popup/overlay": {"type": "boolean"},
  "van-popup/position": {"options": ["top", "bottom", "right", "left"]},
  "van-popup/round": {"type": "boolean"},
  "van-popup/close-on-click-overlay": {"type": "boolean"},
  "van-popup/closeable": {"type": "boolean"},
  "van-popup/safe-area-inset-bottom": {"type": "boolean"},
  "van-popup/safe-area-inset-top": {"type": "boolean"},
  "van-calendar/type": {"options": ["single", "multiple", "range"]},
  "van-calendar/default-date": {"options": ["type", "multiple", "range"]},
  "van-calendar/poppable": {"type": "boolean"},
  "van-calendar/show-mark": {"type": "boolean"},
  "van-calendar/show-title": {"type": "boolean"},
  "van-calendar/show-subtitle": {"type": "boolean"},
  "van-calendar/show-confirm": {"type": "boolean"},
  "van-checkbox/shape": {"options": ["round", "square"]},
  "van-checkbox/value": {"type": "boolean"},
  "van-checkbox/disabled": {"type": "boolean"},
  "van-checkbox/label-disabled": {"type": "boolean"},
  "van-checkbox/use-icon-slot": {"type": "boolean"},
  "van-checkbox-group/disabled": {"type": "boolean"},
  "van-datetime-picker/type": {"options": ["date", "time", "year-month"]},
  "van-datetime-picker/show-toolbar": {"type": "boolean"},
  "van-datetime-picker/loading": {"type": "boolean"},
  "van-field/type": {"options": ["number", "idcard", "textarea", "digit"]},
  "van-field/fixed": {"type": "boolean"},
  "van-field/focus": {"type": "boolean"},
  "van-field/border": {"type": "boolean"},
  "van-field/disabled": {"type": "boolean"},
  "van-field/readonly": {"type": "boolean"},
  "van-field/clearable": {"type": "boolean"},
  "van-field/clickable": {"type": "boolean"},
  "van-field/required": {"type": "boolean"},
  "van-field/center": {"type": "boolean"},
  "van-field/password": {"type": "boolean"},
  "van-field/is-link": {"type": "boolean"},
  "van-field/arrow-direction": {"options": ["left", "up", "down"]},
  "van-field/show-word-limit": {"type": "boolean"},
  "van-field/error": {"type": "boolean"},
  "van-field/error-message-align": {"options": ["center", "right"]},
  "van-field/input-align": {"options": ["center", "right"]},
  "van-field/autosize": {"type": "boolean"},
  "van-field/confirm-hold": {"type": "boolean"},
  "van-field/hold-keyboard": {"type": "boolean"},
  "van-field/adjust-position": {"type": "boolean"},
  "van-field/show-confirm-bar": {"type": "boolean"},
  "van-field/auto-focus": {"type": "boolean"},
  "van-field/disable-default-padding": {"type": "boolean"},
  "van-picker/show-toolbar": {"type": "boolean"},
  "van-picker/loading": {"type": "boolean"},
  "van-radio/disabled": {"type": "boolean"},
  "van-radio/label-disabled": {"type": "boolean"},
  "van-radio/use-icon-slot": {"type": "boolean"},
  "van-radio-group/disabled": {"type": "boolean"},
  "van-rate/allow-half": {"type": "boolean"},
  "van-rate/readonly": {"type": "boolean"},
  "van-rate/disabled": {"type": "boolean"},
  "van-rate/touchable": {"type": "boolean"},
  "van-search/show-action": {"type": "boolean"},
  "van-search/action-text": {"type": "boolean"},
  "van-search/focus": {"type": "boolean"},
  "van-search/error": {"type": "boolean"},
  "van-search/disabled": {"type": "boolean"},
  "van-search/readonly": {"type": "boolean"},
  "van-search/clearable": {"type": "boolean"},
  "van-search/use-action-slot": {"type": "boolean"},
  "van-search/input-align": {"options": ["center", "right"]},
  "van-search/use-left-icon-slot": {"type": "boolean"},
  "van-search/use-right-icon-slot": {"type": "boolean"},
  "van-slider/disabled": {"type": "boolean"},
  "van-stepper/integer": {"type": "boolean"},
  "van-stepper/disabled": {"type": "boolean"},
  "van-stepper/disable-input": {"type": "boolean"},
  "van-stepper/async-change": {"type": "boolean"},
  "van-stepper/show-plus": {"type": "boolean"},
  "van-stepper/show-minus": {"type": "boolean"},
  "van-stepper/disable-plus": {"type": "boolean"},
  "van-stepper/disable-minus": {"type": "boolean"},
  "van-stepper/long-press": {"type": "boolean"},
  "van-switch/loading": {"type": "boolean"},
  "van-switch/disabled": {"type": "boolean"},
  "van-uploader/accept": {"options": ["all", "media", "image", "file", "video"]},
  "van-uploader/sizeType": {"options": ["accept", "image", "original", "compressed"]},
  "van-uploader/preview-image": {"type": "boolean"},
  "van-uploader/preview-full-image": {"type": "boolean"},
  "van-uploader/multiple": {"type": "boolean"},
  "van-uploader/disabled": {"type": "boolean"},
  "van-uploader/show-upload": {"type": "boolean"},
  "van-uploader/deletable": {"type": "boolean"},
  "van-uploader/capture": {"options": ["accept", "image", "capture", "camera"]},
  "van-uploader/image-fit": {"options": ["image", "mode"]},
  "van-uploader/use-before-read": {"type": "boolean"},
  "van-uploader/camera": {"options": ["video", "back", "front"]},
  "van-uploader/compressed": {"type": "boolean"},
  "van-action-sheet/overlay": {"type": "boolean"},
  "van-action-sheet/round": {"type": "boolean"},
  "van-action-sheet/close-on-click-action": {"type": "boolean"},
  "van-action-sheet/close-on-click-overlay": {"type": "boolean"},
  "van-action-sheet/safe-area-inset-bottom": {"type": "boolean"},
  "van-dialog/show": {"type": "boolean"},
  "van-dialog/message-align": {"options": ["left", "right"]},
  "van-dialog/show-confirm-button": {"type": "boolean"},
  "van-dialog/show-cancel-button": {"type": "boolean"},
  "van-dialog/overlay": {"type": "boolean"},
  "van-dialog/close-on-click-overlay": {"type": "boolean"},
  "van-dialog/use-slot": {"type": "boolean"},
  "van-dialog/use-title-slot": {"type": "boolean"},
  "van-dialog/async-close": {"type": "boolean"},
  "van-dropdown-menu/overlay": {"type": "boolean"},
  "van-dropdown-menu/close-on-click-overlay": {"type": "boolean"},
  "van-dropdown-menu/close-on-click-outside": {"type": "boolean"},
  "van-dropdown-item/disabled": {"type": "boolean"},
  "van-loading/vertical": {"type": "boolean"},
  "van-overlay/show": {"type": "boolean"},
  "van-share-sheet/overlay": {"type": "boolean"},
  "van-share-sheet/close-on-click-overlay": {"type": "boolean"},
  "van-share-sheet/safe-area-inset-bottom": {"type": "boolean"},
  "van-swipe-cell/async-close": {"type": "boolean"},
  "van-swipe-cell/disabled": {"type": "boolean"},
  "van-circle/clockwise": {"type": "boolean"},
  "van-collapse/accordion": {"type": "boolean"},
  "van-collapse/border": {"type": "boolean"},
  "van-collapse-item/border": {"type": "boolean"},
  "van-collapse-item/is-link": {"type": "boolean"},
  "van-collapse-item/clickable": {"type": "boolean"},
  "van-collapse-item/disabled": {"type": "boolean"},
  "van-count-down/auto-start": {"type": "boolean"},
  "van-count-down/millisecond": {"type": "boolean"},
  "van-count-down/use-slot": {"type": "boolean"},
  "van-divider/dashed": {"type": "boolean"},
  "van-divider/hairline": {"type": "boolean"},
  "van-divider/content-position": {"options": ["left", "center", "right"]},
  "van-empty/image": {"options": ["error", "network", "search"]},
  "van-notice-bar/mode": {"options": ["closeable", "link"]},
  "van-notice-bar/scrollable": {"type": "boolean"},
  "van-notice-bar/wrapable": {"type": "boolean"},
  "van-progress/inactive": {"type": "boolean"},
  "van-progress/show-pivot": {"type": "boolean"},
  "van-tag/type": {"options": ["primary", "success", "danger", "warning"]},
  "van-tag/size": {"options": ["large", "medium"]},
  "van-tag/plain": {"type": "boolean"},
  "van-tag/round": {"type": "boolean"},
  "van-tag/mark": {"type": "boolean"},
  "van-tag/closeable": {"type": "boolean"},
  "van-grid/border": {"type": "boolean"},
  "van-grid/center": {"type": "boolean"},
  "van-grid/square": {"type": "boolean"},
  "van-grid/clickable": {"type": "boolean"},
  "van-grid/reverse": {"type": "boolean"},
  "van-grid/use-slot": {"type": "boolean"},
  "van-grid-item/dot": {"type": "boolean"},
  "van-grid-item/link-type": {"options": ["redirectTo", "switchTab", "reLaunch"]},
  "van-index-bar/sticky": {"type": "boolean"},
  "van-index-anchor/use-slot": {"type": "boolean"},
  "van-nav-bar/left-arrow": {"type": "boolean"},
  "van-nav-bar/fixed": {"type": "boolean"},
  "van-nav-bar/placeholder": {"type": "boolean"},
  "van-nav-bar/border": {"type": "boolean"},
  "van-nav-bar/safe-area-inset-top": {"type": "boolean"},
  "van-sidebar-item/dot": {"type": "boolean"},
  "van-sidebar-item/disabled": {"type": "boolean"},
  "van-tab/disabled": {"type": "boolean"},
  "van-tab/dot": {"type": "boolean"},
  "van-tabs/animated": {"type": "boolean"},
  "van-tabs/border": {"type": "boolean"},
  "van-tabs/ellipsis": {"type": "boolean"},
  "van-tabs/sticky": {"type": "boolean"},
  "van-tabs/swipeable": {"type": "boolean"},
  "van-tabs/lazy-render": {"type": "boolean"},
  "van-tabbar/fixed": {"type": "boolean"},
  "van-tabbar/placeholder": {"type": "boolean"},
  "van-tabbar/border": {"type": "boolean"},
  "van-tabbar/safe-area-inset-bottom": {"type": "boolean"},
  "van-tabbar-item/dot": {"type": "boolean"},
  "van-area/loading": {"type": "boolean"},
  "van-card/link-type": {"options": ["redirectTo", "switchTab", "reLaunch"]},
  "van-card/lazy-load": {"type": "boolean"},
  "van-submit-bar/disabled": {"type": "boolean"},
  "van-submit-bar/loading": {"type": "boolean"},
  "van-submit-bar/safe-area-inset-bottom": {"type": "boolean"},
  "van-goods-action/safe-area-inset-bottom": {"type": "boolean"},
  "van-goods-action-icon/link-type": {"options": ["redirectTo", "switchTab", "reLaunch"]},
  "van-goods-action-icon/disabled": {"type": "boolean"},
  "van-goods-action-icon/loading": {"type": "boolean"},
  "van-goods-action-button/link-type": {"options": ["redirectTo", "switchTab", "reLaunch"]},
  "van-goods-action-button/type": {"options": ["primary", "warning", "danger"]},
  "van-goods-action-button/plain": {"type": "boolean"},
  "van-goods-action-button/size": {"options": ["normal", "large", "small", "mini"]},
  "van-goods-action-button/disabled": {"type": "boolean"},
  "van-goods-action-button/loading": {"type": "boolean"}
}